# Check if the Certificate CRD is present in the cluster.
{{ $certmgr := lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "certificates.cm.f5co.k8s.f5net.com" }}
{{ $f5cert := lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "certificates.cert-manager.io" }}
{{- if or $certmgr $f5cert }}
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-pccd-grpc-clt
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-pccd-grpc-clt-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate is 1 hour, not configurable
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
---
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-pccd-grpc-svr
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  dnsNames:
    - grpc-pccd-svc
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-pccd-grpc-svr-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate is 1 hour, not configurable
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
---
{{- if and (.Values.afm.fluentbit_sidecar.enabled) (.Values.afm.fluentbit_sidecar.fluentbit.tls.enabled) }}
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-pccdfluentbit-grpc-clt
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-pccdfluentbit-grpc-clt-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate is 360 days, not configurable
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
{{- end }}
{{- end }}
---
#certificate for communication from CWC Orchestrator to Qkview process
{{- if .Values.afm.pccd.f5_csm_qkview.enabled }}
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-f5-afm-pccd-grpc-svr
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  dnsNames:
     - f5-afm.{{ .Release.Namespace }}
     - f5-afm-pccd.{{ .Release.Namespace }}
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-f5-afm-pccd-grpc-svr-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  duration: 1h
  revisionHistoryLimit: 10
{{- end }}