{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.afm.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.afm.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.afm.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.afm.name }}
      {{- if .Values.afm.annotations }}
      annotations:
{{ toYaml .Values.afm.annotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.afm.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.afm.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.afm.tolerations }}
      tolerations:
{{ toYaml .Values.afm.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.afm.affinity }}
      affinity:
{{ toYaml .Values.afm.affinity | indent 8 }}
      {{- end }}
      serviceAccountName: {{ include "afm.serviceAccountName" . }}
      hostNetwork: {{ .Values.afm.hostNetwork }}
      {{- if .Values.afm.podSecurityContext }}
      securityContext:
{{ toYaml .Values.afm.podSecurityContext | indent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: {{ .Values.global.imageCredentials.name }}

      containers:
      {{- if .Values.afm.pccd.enabled }}
      - image: "{{ .Values.afm.pccd.image.repository }}{{if ne .Values.afm.pccd.image.repository ""}}/{{end}}{{ .Values.afm.pccd.image.name }}:{{ .Values.afm.pccd.image.tag }}"
        name: {{ .Values.afm.pccd.name }}
        imagePullPolicy: "{{ .Values.afm.pccd.image.pullPolicy }}"
        {{- if .Values.afm.pccd.resources }}
        resources:
          {{- if .Values.afm.pccd.resources.limits }}
          limits:
            memory: {{ .Values.afm.pccd.resources.limits.memory | default "512Mi" }}
            cpu: {{ .Values.afm.pccd.resources.limits.cpu | default "1" }}
          {{- end }}
          {{- if .Values.afm.pccd.resources.requests }}
          requests:
            memory: {{ .Values.afm.pccd.resources.requests.memory | default "256Mi" }}
            cpu: {{ .Values.afm.pccd.resources.requests.cpu | default "0.5" }}
          {{- end }}
        {{- end }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
          subPath: pccd-tmp
          readOnly: false
        - name: run-dir
          mountPath: /run
          subPath: pccd-run
          readOnly: false
        - name: logs-dir
          mountPath: /logs
          subPath: pccd-logs
          readOnly: false
        - name: var-log-dir
          mountPath: /var/log
          readOnly: false
        - name: tls-pccd-grpc-clt-volume
          mountPath: /tls/pccd/grpc/clt/
          readOnly: true
        - name: tls-pccd-grpc-svr-volume
          mountPath: /tls/pccd/grpc/svr/
          readOnly: true
        {{- if .Values.afm.pccd.f5_csm_qkview.enabled }}
        - name: tls-f5-afm-pccd-grpc-svr-volume
          mountPath: /tls/f5-afm-pccd/grpc/svr
          readOnly: true
        {{- end }}
        {{- if .Values.afm.fluentbit_sidecar.enabled }}
        - name: f5-log-pipes
          mountPath: /var/run/f5
        {{- if .Values.afm.fluentbit_sidecar.fluentbit.tls.enabled }}
        - name: tls-pccdfluentbit-grpc-clt-volume
          mountPath: /tls/pccdluentbit/grpc/clt/
        {{- end }}
        {{- end }}
        {{- if or (eq .Values.global.platformType "robin") (eq .Values.global.platformType "other") }}
        - mountPath: /var/crash
          name: f5-core-store
          readOnly: false
        {{- end }}
        {{- if .Values.afm.pccd.f5_csm_qkview.enabled }}
        ports:
        - containerPort: {{ .Values.afm.pccd.f5_csm_qkview.grpc_port }}
          name: grpc-port
          protocol: TCP
        {{- end }}
        securityContext:
          readOnlyRootFilesystem: {{ .Values.afm.pccd.securityContext.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: {{ .Values.afm.pccd.securityContext.allowPrivilegeEscalation }}
          runAsUser: {{ .Values.afm.pccd.securityContext.runAsUser }}
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GRPC_SRV_PORT
          value: "{{ .Values.afm.pccd.grpc.port | default "8750" }}"
        - name: GRPC_SRV_ENABLED
          value: "true"
        - name: GRPC_SRV_TLS
          value: "true"
        - name: GRPC_REMOTE_DNS
          value: {{ .Values.global.tmm.grpc.name }}
        - name: PATH_CERTS
          value: "/etc/ssl/certs"
        - name: PATH_KEYS
          value: "/etc/ssl/private"
        - name: LOG_LEVEL
          value: {{ if .Values.afm.pccd.debug }}"debug"{{ else }}{{ .Values.afm.pccd.log_level | default "notice" }}{{ end }}
        - name: CFG_DBG_ENABLED
          value: {{ if .Values.afm.pccd.debug }}"true"{{ else }}"false"{{ end }}
        - name: WRITE_BLOB_TO_FILE
          value: {{ if .Values.afm.pccd.debug }}"true"{{ else }}"false"{{ end }}
        - name: MAX_BLOB_SIZE_MB
          value: {{ .Values.afm.pccd.blob.maxFwBlobSizeMb | default "512" | quote  }}
        - name: MAX_NAT_BLOB_SIZE_MB
          value: {{ .Values.afm.pccd.blob.maxNatBlobSizeMb | default "512" | quote }}
        {{- if .Values.afm.fluentbit_sidecar.enabled }}
        - name: EXPORT_PCCD_LOGS
          value: "true"
        {{- end }}
        {{- if .Values.afm.pccd.f5_csm_qkview.enabled }}
        - name: QK_GRPC_PORT
          value: "{{ .Values.afm.pccd.f5_csm_qkview.grpc_port }}"
        - name: QK_TLS_CA_BUNDLE
          value: "/etc/ssl/certs/ca-root-cert.pem"
        - name: QK_TLS_CERT_FILE
          value: "/etc/ssl/certs/server-cert.pem"
        - name: QK_TLS_KEY_FILE
          value: "/etc/ssl/certs/server-key.pem"
        - name: QK_TLS_CERT_RETRY_WAIT
          value: "5s"
        - name: CONTAINER_NAME
          value: f5-afm-pccd
        - name: USING_CERT_ORCHESTRATOR
          value: "true"
        {{- end }}
        - name: GRPC_BLOBD_PORT
          value: "{{ .Values.afm.blobd.grpc.port | default "" }}"
      {{- end }}
      {{- if .Values.afm.pccd.k8sprobes.enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.afm.pccd.grpc.port }}
          initialDelaySeconds: {{ .Values.afm.pccd.k8sprobes.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.afm.pccd.k8sprobes.readinessProbe.periodSeconds }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.afm.pccd.grpc.port }}
          initialDelaySeconds: {{ .Values.afm.pccd.k8sprobes.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.afm.pccd.k8sprobes.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.afm.pccd.k8sprobes.livenessProbe.failureThreshold }}
      {{- end }}
{{- if .Values.afm.fluentbit_sidecar.enabled }}
      - image: "{{ .Values.afm.fluentbit_sidecar.image.repository }}/{{ .Values.afm.fluentbit_sidecar.image.name }}:{{ .Values.afm.fluentbit_sidecar.image.tag }}"
        name: {{ .Values.afm.fluentbit_sidecar.name }}
        imagePullPolicy: {{ .Values.afm.fluentbit_sidecar.image.pullPolicy }}
        resources: {{- toYaml .Values.afm.fluentbit_sidecar.resources | nindent 10 }}
        securityContext:
          readOnlyRootFilesystem: {{ .Values.afm.fluentbit_sidecar.securityContext.readOnlyRootFilesystem }}
          privileged: {{ .Values.afm.fluentbit_sidecar.securityContext.allowPrivilegeEscalation }}
          runAsUser: {{ .Values.afm.fluentbit_sidecar.securityContext.runAsUser }}
        stdin: true
        tty: true
        env:
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: POD
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: tmp
            mountPath: /tmp
            subPath: fluentbit-tmp
            readOnly: false
          - name: run-dir
            mountPath: /run
            subPath: fluentbit-run
            readOnly: false
          - name: logs-dir
            mountPath: /logs
            subPath: fluentbit-logs
            readOnly: false
          - name: f5-log-pipes
            mountPath: /var/run/f5
            readOnly: true
          - name: f5-afm-fluentbit-config
            mountPath: /fluent-bit/etc/
        {{- if .Values.afm.fluentbit_sidecar.fluentbit.tls.enabled }}
          - name: tls-pccdfluentbit-grpc-clt-volume
            mountPath: /tls/pccdfluentbit/grpc/clt/
        {{- end }}
        {{- if or (eq .Values.global.platformType "robin") (eq .Values.global.platformType "other") }}
          - mountPath: /var/crash
            name: f5-core-store
            readOnly: false
        {{- end }}
{{- end }}
      volumes:
      - name: logs-dir
        emptyDir: {}
      - name: run-dir
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: var-log-dir
        emptyDir: {}
      {{- if .Values.afm.pccd.f5_csm_qkview.enabled }}
      - name: tls-f5-afm-pccd-grpc-svr-volume
        secret:
          secretName: tls-f5-afm-pccd-grpc-svr-secret
      {{- end }}
      {{- if or (eq .Values.global.platformType "robin") (eq .Values.global.platformType "other") }}
      - name: f5-core-store
        hostPath:
          path: /home/crash/f5
      {{- end }}
      - name: tls-pccd-grpc-clt-volume
        secret:
          secretName: tls-pccd-grpc-clt-secret
      - name: tls-pccd-grpc-svr-volume
        secret:
          secretName: tls-pccd-grpc-svr-secret
      {{- if .Values.afm.fluentbit_sidecar.enabled }}
      - name: f5-log-pipes
        emptyDir: {}
      - name: f5-afm-fluentbit-config
        configMap:
          name: f5-afm-fluentbit-config
      {{- if .Values.afm.fluentbit_sidecar.fluentbit.tls.enabled }}
      - name: tls-pccdfluentbit-grpc-clt-volume
        secret:
          secretName: tls-pccdfluentbit-grpc-clt-secret
      {{- end }}
      {{- end }}
{{- end }}