{{ $base_port := (.Values.afm.pccd.grpc.port | int )}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.afm.pccd.grpc.name }}
  labels:
    app: {{ .Values.afm.name }}
    type: grpc
spec:
  selector:
    app: {{ .Values.afm.name }}
  ports:
    - protocol: TCP
      name: grpc-pccd
      port: {{ $base_port }}
      targetPort: {{ $base_port }}
---
{{- if (.Values.afm.pccd.f5_csm_qkview.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: f5-afm-pccd
  labels:
    app: {{ .Values.afm.name }}
spec:
  clusterIP: "None"
  ports:
  - port: {{ .Values.afm.pccd.f5_csm_qkview.grpc_port }}
    name: grpc-port
    protocol: TCP
    targetPort: {{ .Values.afm.pccd.f5_csm_qkview.grpc_port }}
  selector:
    app: {{ .Values.afm.name }}
{{- end }}
---
# Backward Compatibility Service
apiVersion: v1
kind: Service
metadata:
  name: f5-afm
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.afm.name }}
spec:
  selector:
    app: {{ .Values.afm.name }}
  ports:
    - protocol: TCP
      name: grpc-pccd
      port: {{ $base_port }}
      targetPort: {{ $base_port }}
