{{- if not .Values.global.controller.Only }}
{{- if and .Values.enabled .Values.ipsd.config.entries}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ipsd.config.name }}
  namespace: {{ .Release.Namespace }}
data:
{{- toYaml .Values.ipsd.config.entries | nindent 2 }}
{{- end }}
{{- end }}
