{{- if and .Values.enabled .Values.global.tmm.grpc.enabled }}
{{ $base_port := (.Values.global.ipsd.grpc.port | int )}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.ipsd.grpc.name }}
  labels:
    app: {{ .Values.ipsd.name }}
    type: grpc
spec:
  selector:
    app: {{ .Values.ipsd.name }}
  ports:
    - protocol: TCP
      name: grpc-ipsd
      port: {{ $base_port }}
      targetPort: {{ $base_port }}
{{- end }}
---
{{- if and .Values.enabled .Values.global.tmm.grpc.enabled }}
{{ $base_port := (.Values.global.ipsd.grpc_stream.port | int )}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.ipsd.grpc_stream.name }}
  labels:
    app: {{ .Values.ipsd.name }}
    type: grpc
spec:
  selector:
    app: {{ .Values.ipsd.name }}
  ports:
    - protocol: TCP
      name: grpc-stream-ipsd
      port: {{ $base_port }}
      targetPort: {{ $base_port }}
{{- end }}
---
{{- if .Values.ipsd.f5_csm_qkview.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: f5-ipsd
  labels:
    app: {{ .Values.ipsd.name }}
spec:
  ports:
  - port: {{ .Values.ipsd.f5_csm_qkview.grpc_port }}
    name: grpc-port-qkview
    protocol: TCP
    targetPort: {{ .Values.ipsd.f5_csm_qkview.grpc_port }}
  selector:
    app: {{ .Values.ipsd.name }}
{{- end }}