{{- if and .Values.enabled .Values.ipsd.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ipsd.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
