{{- if not .Values.global.controller.Only }}
{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ipsd.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.ipsd.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.ipsd.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ipsd.name }}
      {{- if .Values.ipsd.annotations }}
      annotations:
        {{- toYaml .Values.ipsd.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.ipsd.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.ipsd.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.ipsd.tolerations }}
      tolerations:
        {{- toYaml .Values.ipsd.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.ipsd.affinity }}
      affinity:
        {{- toYaml .Values.ipsd.affinity | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ipsd.serviceAccountName" . }}
      hostNetwork: {{ .Values.ipsd.hostNetwork }}
      imagePullSecrets:
        - name: {{ .Values.global.imageCredentials.name }}
      containers:
      - image: "{{ .Values.ipsd.image.repository }}{{if ne .Values.ipsd.image.repository ""}}/{{end}}{{ .Values.ipsd.image.name }}:{{ .Values.ipsd.image.tag }}"
        name: {{ .Values.ipsd.name }}
        ports:
        - containerPort: {{ .Values.ipsd.f5_csm_qkview.grpc_port }}
          name: grpc-port
          protocol: TCP
        imagePullPolicy: "{{ .Values.ipsd.image.pullPolicy }}"
        {{- if .Values.ipsd.resources }}
        resources:
          {{- if .Values.ipsd.resources.limits }}
          limits:
            memory: {{ .Values.ipsd.resources.limits.memory | default "512Mi" }}
            cpu: {{ .Values.ipsd.resources.limits.cpu | default "1" }}
          {{- end }}
          {{- if .Values.ipsd.resources.requests }}
          requests:
            memory: {{ .Values.ipsd.resources.requests.memory | default "256Mi" }}
            cpu: {{ .Values.ipsd.resources.requests.cpu | default "0.5" }}
          {{- end }}
        {{- end }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
          readOnly: false
        - name: run-dir
          mountPath: /run
          readOnly: false
        - name: logs-dir
          mountPath: /logs
          readOnly: false
        - name: var-log-dir
          mountPath: /var/log
          readOnly: false
        {{- include "volumeMounts.spk" . | nindent 8 }}
        {{- if .Values.ipsd.f5_csm_qkview.enabled }}
        - name: tls-ipsdqkview-grpc-svr-volume
          mountPath: /tls/ipsdqkview/grpc/svr
          readOnly: true
        {{- end }}
        {{- if or (eq .Values.global.platformType "robin") (eq .Values.global.platformType "other") }}
        - mountPath: /var/crash
          name: f5-core-store
          readOnly: false
        {{- end }}
        - name: tls-ipsd-grpc-clt-volume
          mountPath: /tls/ipsd/grpc/clt/
          readOnly: true
        - name: tls-ipsd-grpc-svr-volume
          mountPath: /tls/ipsd/grpc/svr/
          readOnly: true
        {{- if .Values.ipsd.fluentbit_sidecar.enabled }}
        - name: f5-log-pipes
          mountPath: /var/run/f5
        {{- end }}
        securityContext:
          readOnlyRootFilesystem: {{ .Values.ipsd.securityContext.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: {{ .Values.ipsd.securityContext.allowPrivilegeEscalation }}
          runAsUser: {{ .Values.ipsd.securityContext.runAsUser }}
        env:
        - name: FLUENTBIT_ENABLED
          value: {{ if .Values.ipsd.fluentbit_sidecar.enabled }}"true"{{ else }}"false"{{ end }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GRPC_SRV_PORT
          value: "{{ .Values.global.ipsd.grpc.port | default "8750" }}"
        - name: GRPC_STREAM_SRV_PORT
          value: "{{ .Values.global.ipsd.grpc_stream.port | default "8770" }}"
        - name: GRPC_SRV_ENABLED
          value: "true"
        - name: GRPC_SRV_TLS
          value: "true"
        - name: GRPC_SRV_CA
          value: {{ .Values.global.ipsd.grpc.ca | default "ca_root.crt" }}
        - name: GRPC_SRV_CERT
          value: {{ .Values.global.ipsd.grpc.cert | default "grpc-svc.crt" }}
        - name: GRPC_SRV_KEY
          value: {{ .Values.global.ipsd.grpc.key | default "grpc-svc.key" }}
        - name: GRPC_CLIENT_CA
          value: {{ .Values.global.ipsd.grpc.client_ca | default "ca_root.crt" }}
        - name: GRPC_CLIENT_CERT
          value: {{ .Values.global.ipsd.grpc.client_cert | default "grpc-ipsd-client.crt" }}
        - name: GRPC_CLIENT_KEY
          value: {{ .Values.global.ipsd.grpc.client_key | default "grpc-ipsd-client.key" }}
        - name: GRPC_REMOTE_DNS
          value: {{ .Values.global.tmm.grpc.name }}
        - name: GRPC_BLOBD_PORT
          value: "{{ .Values.global.blobd.grpc.port | default "9222" }}"
        - name: PATH_CERTS
          value: "/etc/ssl/certs"
        - name: PATH_KEYS
          value: "/etc/ssl/private"
        - name: CFG_DBG_ENABLED
          value: {{ if .Values.ipsd.debug }}"true"{{ else }}"false"{{ end }}
        - name: WRITE_BLOB_TO_FILE
          value: {{ if .Values.ipsd.debug }}"true"{{ else }}"false"{{ end }}
        {{- if .Values.ipsd.f5_csm_qkview.enabled }}
        {{- include "env.spk" (dict "cVersion" .Values.ipsd.image.tag ) | nindent 8 }} 
        - name: QK_GRPC_PORT
          value: "{{ .Values.ipsd.f5_csm_qkview.grpc_port }}"
        - name: QK_TLS_CA_BUNDLE
          value: "/etc/ssl/certs/ca-root-cert.pem"
        - name: QK_TLS_CERT_FILE
          value: "/etc/ssl/certs/server-cert.pem"
        - name: QK_TLS_KEY_FILE
          value: "/etc/ssl/certs/server-key.pem"
        - name: QK_TLS_CERT_RETRY_WAIT
          value: "5s"
        - name: CONTAINER_NAME
          value: "ipsdqkview"
        - name: USING_CERT_ORCHESTRATOR
          value: "true"
        {{- else }}  
        {{- include "env.spk" (dict "cName" .Values.ipsd.name "cVersion" .Values.ipsd.image.tag ) | nindent 8 }} 
        {{- end }}
        {{- if .Values.ipsd.k8sprobes.enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.ipsd.grpc.port }}
          initialDelaySeconds: {{ .Values.ipsd.k8sprobes.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.ipsd.k8sprobes.readinessProbe.periodSeconds }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.ipsd.grpc.port }}
          initialDelaySeconds: {{ .Values.ipsd.k8sprobes.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.ipsd.k8sprobes.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.ipsd.k8sprobes.livenessProbe.failureThreshold }}
        {{- end }}
      {{- if .Values.ipsd.fluentbit_sidecar.enabled }}
      - image: "{{ .Values.ipsd.fluentbit_sidecar.image.repository }}/{{ .Values.ipsd.fluentbit_sidecar.image.name }}:{{ .Values.ipsd.fluentbit_sidecar.image.tag }}"
        name: {{ .Values.ipsd.fluentbit_sidecar.name }}
        imagePullPolicy: {{ .Values.ipsd.fluentbit_sidecar.image.pullPolicy }}
        resources: {{- toYaml .Values.ipsd.fluentbit_sidecar.resources | nindent 10 }}
        securityContext:
          readOnlyRootFilesystem: {{ .Values.ipsd.securityContext.readOnlyRootFilesystem }}
          privileged: {{ .Values.ipsd.securityContext.privileged }}
          runAsUser: {{ .Values.ipsd.securityContext.runAsUser }}  
        stdin: true
        tty: true
        env: {{- toYaml .Values.ipsd.fluentbit_sidecar.env | nindent 10 }}
        volumeMounts: {{- toYaml .Values.ipsd.fluentbit_sidecar.volumeMounts | nindent 10 }}
        {{- if .Values.ipsd.fluentbit_sidecar.fluentbit.tls.enabled }}
          - name: tls-ipsdfluentbit-grpc-clt-volume
            mountPath: /tls/ipsdfluentbit/grpc/clt/
        {{- end }}
      {{- end }}
      volumes:
      {{- include "volumes.spk" . | nindent 6 }}
      - name: logs-dir
        emptyDir: {}
      - name: run-dir
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: var-log-dir
        emptyDir: {}
      {{- if or (eq .Values.global.platformType "robin") (eq .Values.global.platformType "other") }}
      - name: f5-core-store
        hostPath:
          path: /home/crash/f5
      {{- end }}
      - name: tls-ipsd-grpc-clt-volume
        secret:
          secretName: tls-ipsd-grpc-clt-secret
      - name: tls-ipsd-grpc-svr-volume
        secret:
          secretName: tls-ipsd-grpc-svr-secret
      {{- if .Values.ipsd.fluentbit_sidecar.enabled }}
      - name: f5-log-pipes
        emptyDir: {}
      - name: f5-ipsd-fluentbit-config
        configMap:
          name: f5-ipsd-fluentbit-config
      {{- if .Values.ipsd.fluentbit_sidecar.fluentbit.tls.enabled }}
      - name: tls-ipsdfluentbit-grpc-clt-volume
        secret: 
          secretName: tls-ipsdfluentbit-grpc-clt-secret
      {{- end }}
      {{- end }}
      {{- if .Values.ipsd.f5_csm_qkview.enabled }}
      - name: tls-ipsdqkview-grpc-svr-volume
        secret:
          secretName: tls-ipsdqkview-grpc-svr-secret
      {{- end }}

{{- end }}
{{- end }}
