{{- if not .Values.global.controller.Only }}
{{- if .Values.enabled }}
apiVersion: {{ .Values.downloader.apiVersion }}
kind: Deployment
metadata:
  name: {{ .Values.downloader.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.downloader.name }}
spec:
  replicas: {{ .Values.downloader.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.downloader.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.downloader.name }}
      {{- if .Values.downloader.annotations }}
      annotations:
        {{- toYaml .Values.downloader.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.downloader.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.downloader.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.downloader.tolerations }}
      tolerations:
        {{- toYaml .Values.downloader.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.downloader.affinity }}
      affinity:
        {{- toYaml .Values.downloader.affinity | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "downloader.serviceAccountName" . }}
      securityContext:
        fsGroup: {{ .Values.downloader.securityContext.fsGroup }}
      hostNetwork: {{ .Values.downloader.hostNetwork }}
      imagePullSecrets:
        - name: {{ .Values.global.imageCredentials.name }}
      containers:
      - image: "{{ .Values.downloader.image.repository }}{{if ne .Values.downloader.image.repository ""}}/{{end}}{{ .Values.downloader.image.name }}:{{ .Values.downloader.image.tag }}"
        name: {{ .Values.downloader.name }}
        imagePullPolicy: "{{ .Values.downloader.image.pullPolicy }}"
        {{- if .Values.downloader.resources }}
        resources:
          {{- if .Values.downloader.resources.limits }}
          limits:
            memory: {{ .Values.downloader.resources.limits.memory | default "2048Mi" }}
            cpu: {{ .Values.downloader.resources.limits.cpu | default "1" }}
          {{- end }}
          {{- if .Values.downloader.resources.requests }}
          requests:
            memory: {{ .Values.downloader.resources.requests.memory | default "1024Mi" }}
            cpu: {{ .Values.downloader.resources.requests.cpu | default "0.5" }}
          {{- end }}
        {{- end }}
        volumeMounts:
        {{- include "volumeMounts.spk" . | nindent 8 }}
        {{- if .Values.downloader.f5_csm_qkview.enabled }}
        - name: tls-qkviewdownloader-grpc-svr-volume
          mountPath: /tls/qkviewdownloader/grpc/svr
          readOnly: true
        {{- end }}
{{- if (eq .Values.global.platformType "robin") }}
        - mountPath: /var/crash
          name: f5-core-store
          readOnly: false
{{- end }}
        - name: tls-downloader-grpc-clt-volume
          mountPath: /tls/downloader/grpc/clt/
          readOnly: true
        - name: tls-downloader-grpc-svr-volume
          mountPath: /tls/downloader/grpc/svr/
          readOnly: true
        - name: tls-downloader-amqp-clt-volume
          mountPath: /tls/downloader/amqp/clt/
          readOnly: true
        - name: ipi-feedlist-credentials-volume
          mountPath: /etc/credentials/ipi-feedlist/
          readOnly: true
        - name: tmp
          mountPath: /tmp
          readOnly: false
        - mountPath: /run
          name: run
          readOnly: false
        - mountPath: /var/run/bigip-next-qkview-collect-daemon
          name: qkview
          readOnly: false
        {{- if .Values.downloader.fluentbit_sidecar.enabled }}
        - name: f5-log-pipes
          mountPath: /var/run/f5
        {{- end }}
        - name: downloader-storage
          mountPath: /var/downloader-localfile-upload
        - name: downloader-data
          mountPath: /data
        {{- if .Values.downloader.f5_csm_qkview.enabled }}
        ports:
        - containerPort: {{ .Values.downloader.f5_csm_qkview.grpc_port }}
          name: grpc-port
          protocol: TCP
        {{- end }}
        securityContext:
          readOnlyRootFilesystem: {{ .Values.downloader.securityContext.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: {{ .Values.downloader.securityContext.allowPrivilegeEscalation }}
          runAsUser: {{ .Values.downloader.securityContext.runAsUser }}
          runAsGroup: {{ .Values.downloader.securityContext.runAsGroup }}
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RABBITMQ_NAMESPACE
          value: {{ .Values.downloader.rabbitmqNamespace }}
        - name: WEBROOT_DEVICE
          value: {{ .Values.downloader.webRootDevice | default "WR-URLCAT-Z105" }}
        - name: UUID
          value: {{ .Values.downloader.uuid | default "" }}
        - name: GRPC_SRV_PORT
          value: "{{ .Values.global.downloader.grpc.port | default "8750" }}"
        - name: GRPC_SRV_ENABLED
          value: "true"
        - name: GRPC_SRV_TLS
          value: "true"
        - name: GRPC_SRV_CA
          value: {{ .Values.global.downloader.grpc.ca | default "ca_root.crt" }}
        - name: GRPC_SRV_CERT
          value: {{ .Values.global.downloader.grpc.cert | default "grpc-svc.crt" }}
        - name: GRPC_SRV_KEY
          value: {{ .Values.global.downloader.grpc.key | default "grpc-svc.key" }}
        - name: GRPC_CLIENT_CA
          value: {{ .Values.global.downloader.grpc.client_ca | default "ca_root.crt" }}
        - name: GRPC_CLIENT_CERT
          value: {{ .Values.global.downloader.grpc.client_cert | default "grpc-downloader-client.crt" }}
        - name: GRPC_CLIENT_KEY
          value: {{ .Values.global.downloader.grpc.client_key | default "grpc-downloader-client.key" }}
        - name: GRPC_REMOTE_DNS
          value: {{ .Values.global.tmm.grpc.name }}
        - name: PATH_CERTS
          value: "/etc/ssl/certs"
        - name: PATH_KEYS
          value: "/etc/ssl/private"
        - name: CFG_DBG_ENABLED
          value: {{ if .Values.downloader.debug }}"true"{{ else }}"false"{{ end }}
        {{- if .Values.downloader.f5_csm_qkview.enabled }}
        {{- include "env.spk" (dict "cVersion" .Values.downloader.image.tag ) | nindent 8 }}
        - name: QK_GRPC_PORT
          value: "{{ .Values.downloader.f5_csm_qkview.grpc_port }}"
        - name: QK_TLS_CA_BUNDLE
          value: "/etc/ssl/certs/ca-root-cert.pem"
        - name: QK_TLS_CERT_FILE
          value: "/etc/ssl/certs/server-cert.pem"
        - name: QK_TLS_KEY_FILE
          value: "/etc/ssl/certs/server-key.pem"
        - name: QK_TLS_CERT_RETRY_WAIT
          value: "5s"
        - name: CONTAINER_NAME
          value: qkviewdownloader
        - name: USING_CERT_ORCHESTRATOR
          value: "true"
        {{- else }}
        {{- include "env.spk" (dict "cName" .Values.downloader.name "cVersion" .Values.downloader.image.tag ) | nindent 8 }}  
        {{- end }}
        - name: FLUENTBIT_ENABLED
          value: {{ if .Values.downloader.fluentbit_sidecar.enabled }}"true"{{ else }}"false"{{ end }}
        {{- if .Values.downloader.k8sprobes.enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.global.downloader.grpc.port }}
          initialDelaySeconds: {{ .Values.downloader.k8sprobes.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.downloader.k8sprobes.readinessProbe.periodSeconds }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.global.downloader.grpc.port }}
          initialDelaySeconds: {{ .Values.downloader.k8sprobes.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.downloader.k8sprobes.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.downloader.k8sprobes.livenessProbe.failureThreshold }}
        {{- end }}
      {{- if .Values.downloader.fluentbit_sidecar.enabled }}
      - image: "{{ .Values.downloader.fluentbit_sidecar.image.repository }}/{{ .Values.downloader.fluentbit_sidecar.image.name }}:{{ .Values.downloader.fluentbit_sidecar.image.tag }}"
        name: {{ .Values.downloader.fluentbit_sidecar.name }}
        imagePullPolicy: {{ .Values.downloader.fluentbit_sidecar.image.pullPolicy }}
        securityContext:
          readOnlyRootFilesystem: {{ .Values.downloader.securityContext.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: {{ .Values.downloader.securityContext.allowPrivilegeEscalation }}
          privileged: {{ .Values.downloader.securityContext.privileged }}
          runAsUser: {{ .Values.downloader.securityContext.runAsUser }}  
          runAsGroup: {{ .Values.downloader.securityContext.runAsGroup }}
        stdin: true
        tty: true
        env: {{- toYaml .Values.downloader.fluentbit_sidecar.env | nindent 12 }}
        volumeMounts: {{- toYaml .Values.downloader.fluentbit_sidecar.volumeMounts | nindent 12 }}
        {{- if .Values.downloader.fluentbit_sidecar.fluentbit.tls.enabled }}
            - name: tls-downloaderfluentbit-grpc-clt-volume
              mountPath: /tls/downloaderfluentbit/grpc/clt
        {{- end }}
            - mountPath: /tmp
              name: tmp
              subPath: fluentbit-tmp
            - mountPath: /run
              name: run
              subPath: fluentbit-run
            - mountPath: /logs
              name: logs
              subPath: fluentbit-logs
            - mountPath: /var/log
              name: var-log
              subPath: fluentbit-var-log
      {{- end }}
      volumes:
      {{- include "volumes.spk" . | nindent 6 }}
      {{- if .Values.downloader.f5_csm_qkview.enabled }}
      - name: tls-qkviewdownloader-grpc-svr-volume
        secret:
          secretName: tls-qkviewdownloader-grpc-svr-secret
      {{- end }}
{{- if (eq .Values.global.platformType "robin") }}
      - name: f5-core-store
        hostPath:
          path: /home/crash/f5
{{- end }}
      - name: tls-downloader-grpc-clt-volume
        secret:
          secretName: tls-downloader-grpc-clt-secret
      - name: tls-downloader-grpc-svr-volume
        secret:
          secretName: tls-downloader-grpc-svr-secret
      - name: tls-downloader-amqp-clt-volume
        secret:
          secretName: tls-downloader-amqp-clt-secret
      - name: ipi-feedlist-credentials-volume
        secret:
          secretName: ipi-feedlist-credentials-secret
          defaultMode: 0440
      - name: downloader-data
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: run
        emptyDir: {}
      - name: qkview
        emptyDir: {}
      - emptyDir: {}
        name: logs
      - emptyDir: {}
        name: var-log
      {{- if .Values.downloader.storage.enabled }}
      - name: downloader-storage
        persistentVolumeClaim:
          claimName: downloader-storage
      {{- else }}
      - name: downloader-storage
        emptyDir: {}
      {{- end }}
      {{- if .Values.downloader.fluentbit_sidecar.enabled }}
      - name: f5-log-pipes
        emptyDir: {}
      - name: f5-downloader-fluentbit-config
        configMap:
          name: f5-downloader-fluentbit-config
      {{- if .Values.downloader.fluentbit_sidecar.fluentbit.tls.enabled }}
      - name: tls-downloaderfluentbit-grpc-clt-volume
        secret:
          secretName: tls-downloaderfluentbit-grpc-clt-secret
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
