{{- define "f5-toda-logging.deployment.tpl" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    toda.f5.com/template: "deploy"
    toda.f5.com/version: {{ .Chart.Version }}
  name: f5-toda-tmstatsd
  labels:
    run: f5-tmstatsd
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: f5-tmm
  template:
    spec:
      containers: null
    metadata:
      labels:
        run: f5-tmstatsd
      annotations:
        toda.f5.com/template: "deploy"
        toda.f5.com/version: {{ .Chart.Version }}
{{- end -}}
{{- define "f5-toda-logging.deployment" -}}
  {{- if (index (first .) "Values" "f5-toda-logging" "enabled") -}}
    {{- template "f5-toda-logging.util.merge" (append . "f5-toda-logging.deployment.tpl") -}}
  {{- else -}}
    {{- /* render original yaml */ -}}
    {{- include (last .) (first .) -}}
  {{- end -}}
{{- end -}}
