{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app: opentelemetry
    component: otel-collector
    metrics-prometheus: publish
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  replicas: 1
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
        metrics-prometheus: publish
      {{- if .Values.pod.annotations }}
      annotations:
        {{- toYaml .Values.pod.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if and .Values.global.imageCredentials .Values.global.imageCredentials.name }}
      imagePullSecrets:
        - name: {{ .Values.global.imageCredentials.name }}
      {{- else }}
      imagePullSecrets: []
      {{- end }}
      serviceAccountName: {{ include "stats-collector.serviceAccountName" . }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
      automountServiceAccountToken: false
      containers:
      - args:
          - --config
          - /etc/conf/otel-collector-conf
          {{- if .Values.otelCustomConf }}
          - --config
          - /etc/conf/custom-otel-collector-conf
          {{- end }}
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        name: otel-collector
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        {{- if .Values.resources }}
        resources:
          {{- if .Values.resources.limits }}
          limits:
            memory: {{ .Values.resources.limits.memory | default "512Mi" }}
            cpu: {{ .Values.resources.limits.cpu | default "1" }}
          {{- end }}
          {{- if .Values.resources.requests }}
          requests:
            memory: {{ .Values.resources.requests.memory | default "256Mi" }}
            cpu: {{ .Values.resources.requests.cpu | default "0.5" }}
          {{- end }}
        {{- end }}
        securityContext:
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 4317
          protocol: TCP
        - containerPort: 8006
          protocol: TCP
        - containerPort: 8888
          protocol: TCP
        - containerPort: 9090
          protocol: TCP
        env:
        {{- include "env.spk" (dict "cName" "otel-collector" "cVersion" .Values.image.tag ) | nindent 8 }}
        volumeMounts:
        {{- include "volumeMounts.spk" . | nindent 8 }}
        {{- if .Values.extra.volumeMounts }}
        {{- toYaml .Values.extra.volumeMounts | nindent 8 }}
        {{- end }}
        - name: otel-collector-conf-vol
          mountPath: /etc/conf
          readOnly: true
        - name: tls-otel-grpc-svr-volume
          mountPath: /tls/otel/grpc/svr
          readOnly: true
        - name: external-otelsvr-volume
          mountPath: /external/otelsvr
          readOnly: true
        - name: shared-tmp
          mountPath: /tmp
      volumes:
        {{- include "volumes.spk" . | nindent 8 }}
        {{- if .Values.extra.volumes }}
        {{- toYaml .Values.extra.volumes | nindent 8 }}
        {{- end }}
        - name: otel-collector-conf-vol
          configMap:
            name: f5-otel-collector-conf
        - name: tls-otel-grpc-svr-volume
          secret:
            secretName: tls-otel-grpc-svr-secret
        - name: external-otelsvr-volume
          secret:
            secretName: external-otelsvr-secret
        - name: shared-tmp
          emptyDir: {}
{{- end }}
