apiVersion: v2
appVersion: 1.0.7-0.0.4
dependencies:
- name: spk-common
  repository: ""
  version: 1.3.5
description: A Helm chart for f5-stats_collector
name: f5-stats_collector
type: application
version: 1.0.7-0.0.4
