
enabled: false

downloader:
  name: f5-downloader
  debug: false
  rabbitmqNamespace: "cnf-telemetry"

  k8sprobes:
    enabled: true
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 1
  
  storage:
    enabled: true
    storageClassName: standard
    access: ReadWriteOnce
  
  f5_csm_qkview:
    enabled: true
    grpc_port: 19887

  # ## Downloader pod assignment/selector values.
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # ## Downloader pod replica count
  replicas: 1

  # ## Downloader deployment api version
  apiVersion: apps/v1

  # ## Enables the Downloader pods to use the host's network namespace.
  hostNetwork: false

  # ## Downloader annotations
  annotations: {}

  # ## Downloader image values
  image:
    name: f5-downloader
    tag: v0.27.9-0.0.12
    pullPolicy: IfNotPresent

  # ## Downloader security values
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsUser: 7053
    runAsGroup: 7053
    fsGroup: 7053
    privileged: ""

  ## below params can be used as downloader.serviceAccount.name
  serviceAccount:
    create: true
    ## The name of the service account to use.
    ## If not set and create is true, a name is generated using .Values.downloader.name.
    # name: ""  

  # ## Downloader resources
  resources:
    limits:
      cpu: "1"
      memory: "2000Mi"
    requests:
      cpu: "500m"
      memory: "1000Mi"
  # ## Fluentbit sidecar values
  fluentbit_sidecar:
    enabled: false
    name: fluentbit
    image:
        name: f5-fluentbit
        tag: v1.2.8-0.0.5
        pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.25"
        memory: "256Mi"
    ## Environment variables used in config file for fluentbit
    env:
      - name: NODE
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: POD_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.uid
      - name: POD
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
    volumeMounts:
      - name: f5-log-pipes
        mountPath: /var/run/f5
        readOnly: true
      - name: f5-downloader-fluentbit-config
        mountPath: /fluent-bit/etc/
    fluentbit:
      ## Interval to flush output (seconds)
      flush_interval: 1
      ## Error/warning/info/debug/trace
      logLevel: info
      ## Pipe reading parameters
      input:
        pipes:
          bufSize: 8096
          intervalSec: 1
          intervalNsec: 0
      tls:
        enabled: false
        ## TLS debug verbosity level, values: 0 (No debug), 1 (Error), 2 (State change), 3 (Informational) and 4 (Verbose)
        debug: 1
        ## Force certificate validation
        verify: Off
        ## key string known by the remote Fluentd used for authorization.
        shared_key: f5-toda-shared-key

    fluentd:
      host: '127.0.0.1'
      port: 54321
      targetport: 24224

global:
  ## enum for identifying platform type. By default it is set to other. User needs to define the platform type (ocp,robin,tanzu,mbip-ve) during deployment.
  platformType: other
  serviceAccount:
    name:
    create: false
  certmgr:
    external: false
    ## If using an external cert-manager installation, the issuerRef must be populated with the required fields.
    # issuerRef:
    #   name: cert-issuer
    #   kind: Issuer
    #   namespace: cert-manager

  # The below global variables are being used by ipsd, afm and downloader subcharts only.

  controller:
    Only: false
    crdupdater:
      enabled: false
      grpc:
        port: 8750
  imageCredentials:
    name: f5ingress-regsecret
  tmm:
    grpc:
      enabled: true
      name: grpc-svc
  blobd:
    enabled: false
    grpc:
      port: 9222
  afm:
    enabled: false
    pccd:
      enabled: false
      grpc:
        name: grpc-pccd-svc
  ### Downloader GRPC values
  downloader:
    grpc:
      name: grpc-downloader-svc
      port: 8750
      ca: "ca_root.crt"
      cert: "grpc-svc.crt"
      key: "grpc-svc.key"
      client_ca: "ca_root.crt"
      client_cert: "grpc-downloader-client.crt"
      client_key: "grpc-downloader-client.key"

spk-common:
  skipF5logCreation: true      
