# =============================================================================
# TERRAGRUNT BACKEND CONFIGURATION - Local File System
# Generated by BNK-Forge
# For on-premises or development environments
# =============================================================================

remote_state {
  backend = "local"

  config = {
    # Local state file path
    # Organized by module path to prevent conflicts
    path = "${get_repo_root()}/terraform.tfstate.d/${path_relative_to_include()}/terraform.tfstate"
  }

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

# =============================================================================
# NOTES
# =============================================================================
#
# WARNING: Local backend is NOT recommended for production use!
#
# Limitations:
# - No state locking (risk of concurrent modification)
# - No team collaboration support
# - State stored on local filesystem (backup responsibility)
#
# Use cases:
# - Development/testing environments
# - Single-user deployments
# - On-premises without remote state infrastructure
#
# For production, consider:
# - AWS S3 backend (if using AWS)
# - Consul backend (for on-premises with Consul)
# - Terraform Cloud/Enterprise
#
# State file location:
# - Root: <repo>/terraform.tfstate.d/
# - Per module: <repo>/terraform.tfstate.d/<module-path>/terraform.tfstate
#
# Backup recommendations:
# - Add terraform.tfstate.d/ to version control
# - Regular backups of terraform.tfstate.d/ directory
# - Consider using git-crypt for sensitive state values
#
# =============================================================================
