# =============================================================================
# TERRAGRUNT BACKEND CONFIGURATION - AWS S3
# Generated by BNK-Forge
# =============================================================================

remote_state {
  backend = "s3"

  config = {
    # S3 Bucket Configuration
    bucket = "{{S3_BUCKET_NAME}}"  # CHANGE ME: Your Terraform state bucket
    key    = "${path_relative_to_include()}/terraform.tfstate"
    region = "{{AWS_REGION}}"      # CHANGE ME: AWS region for state bucket

    # Encryption
    encrypt = true

    # State Locking
    dynamodb_table = "{{DYNAMODB_TABLE}}"  # CHANGE ME: DynamoDB table for state locking

    # AWS Profile (optional - remove if using IAM role/instance profile)
    profile = "{{AWS_PROFILE}}"  # CHANGE ME: Your AWS CLI profile

    # Advanced S3 options (optional)
    # kms_key_id              = "arn:aws:kms:region:account:key/id"  # For KMS encryption
    # skip_credentials_validation = false
    # skip_metadata_api_check    = false
    # skip_region_validation     = false

    # Workspace configuration (optional)
    # workspace_key_prefix = "workspaces"
  }

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

# =============================================================================
# SETUP INSTRUCTIONS
# =============================================================================
#
# 1. Create S3 bucket for Terraform state:
#    aws s3api create-bucket \
#      --bucket {{S3_BUCKET_NAME}} \
#      --region {{AWS_REGION}} \
#      --create-bucket-configuration LocationConstraint={{AWS_REGION}}
#
# 2. Enable versioning on the bucket:
#    aws s3api put-bucket-versioning \
#      --bucket {{S3_BUCKET_NAME}} \
#      --versioning-configuration Status=Enabled
#
# 3. Enable encryption on the bucket:
#    aws s3api put-bucket-encryption \
#      --bucket {{S3_BUCKET_NAME}} \
#      --server-side-encryption-configuration \
#      '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
#
# 4. Create DynamoDB table for state locking:
#    aws dynamodb create-table \
#      --table-name {{DYNAMODB_TABLE}} \
#      --attribute-definitions AttributeName=LockID,AttributeType=S \
#      --key-schema AttributeName=LockID,KeyType=HASH \
#      --billing-mode PAY_PER_REQUEST \
#      --region {{AWS_REGION}}
#
# 5. Block public access to the bucket:
#    aws s3api put-public-access-block \
#      --bucket {{S3_BUCKET_NAME}} \
#      --public-access-block-configuration \
#      "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
#
# =============================================================================
