controller:
  createTmmLBService: false
  f5_lic_helper:
    enabled: true
    image:
      repository: repo.f5.com/images
    name: f5-lic-helper
    rabbitmqCerts:
      ca_root_cert: null
      client_cert: null
      client_key: null
    rabbitmqNamespace: f5-utils
  fluentbit_sidecar:
    enabled: false
    fluentd:
      host: localhost
  grafana:
    enabled: false
    port: 32000
  image:
    repository: repo.f5.com/images
  otel_sidecar:
    enabled: false
    prometheus_nodePort: 30000
  prometheus:
    enabled: false
    port: 30000
  tmm_pod_manager:
    image:
      repository: repo.f5.com/images
  watchNamespace: f5-spk
f5-tmm:
  blobd:
    enabled: false
    image:
      repository: repo.f5.com/images
  cert-orchestrator:
    enabled: true
  debug:
    image:
      repository: repo.f5.com/images
    rabbitmqNamespace: f5-utils
  enabled: true
  f5-toda-logging:
    enabled: false
    fluentbit:
      tls:
        enabled: false
    fluentd:
      host: f5-toda-fluentd.f5-utils.svc.cluster.local.
      port: 54321
    tmstats:
      config:
        image:
          repository: repo.f5.com/images
      enabled: false
  tmm:
    cniNetworks: f5-spk/external-netdevice, f5-spk/internal-netdevice
    customEnvVars:
    - name: ROBIN_VFIO_RESOURCE_1
      value: external_netdevice
    - name: ROBIN_VFIO_RESOURCE_2
      value: internal_netdevice
    - name: PCIDEVICE_INTEL_COM_EXTERNAL_NETDEVICE
      value: "0000:00:07.0"
    - name: PCIDEVICE_INTEL_COM_INTERNAL_NETDEVICE
      value: "0000:00:06.0"
    - name: TMM_IGNORE_GATEWAYS
      value: "TRUE"
    - name: PAL_CPU_SET
      value: "0"
    - name: TMM_MAPRES_IGNORE_MEM_LIMIT
      value: "TRUE"
    - name: SESSIONDB_EXTERNAL_SERVICE
      value: f5-dssm-sentinel.f5-utils.svc.cluster.local:26379
    debug:
      enabled: true
    dynamicRouting:
      enabled: false
    grpc:
      enabled: true
    hugepages:
      enabled: true
    icni2:
      enabled: false
    image:
      repository: repo.f5.com/images
    nodeSelector:
      node-type: high-performance
    resources:
      limits:
        cpu: 2
        hugepages-2Mi: 3Gi
        memory: 3Gi
    tlsStore:
      enabled: false
    tolerations:
    - effect: NoSchedule
      key: f5.com/spk-node
      operator: Equal
      value: "true"
    - effect: NoSchedule
      key: high-performance
      operator: Equal
      value: "true"
global:
  imageCredentials:
    name: far-secret
imageCredentials:
  name: far-secret
