{{- if not .Values.global.controller.Only }}
{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dwbld.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.dwbld.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.dwbld.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dwbld.name }}
      {{- if .Values.dwbld.annotations }}
      annotations:
        {{ toYaml .Values.dwbld.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.dwbld.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.dwbld.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.dwbld.tolerations }}
      tolerations:
        {{ toYaml .Values.dwbld.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.dwbld.affinity }}
      affinity:
        {{ toYaml .Values.dwbld.affinity | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dwbld.serviceAccountName" . }}
      hostNetwork: {{ .Values.dwbld.hostNetwork }}
      imagePullSecrets:
        - name: {{ .Values.global.imageCredentials.name }}
      containers:
      - image: "{{ .Values.dwbld.image.repository | required ".Values.dwbld.image.repository is required." }}/{{ .Values.dwbld.image.name }}:{{ .Values.dwbld.image.tag }}"
        name: {{ .Values.dwbld.name }}
        ports:
        - containerPort: {{ .Values.dwbld.f5_csm_qkview.grpc_port }}
          name: grpc-port
          protocol: TCP 
        imagePullPolicy: "{{ .Values.dwbld.image.pullPolicy }}"
        {{- if .Values.dwbld.resources }}
        resources:
          {{- if .Values.dwbld.resources.limits }}
          limits:
            memory: {{ .Values.dwbld.resources.limits.memory | default "256Mi" }}
            cpu: {{ .Values.dwbld.resources.limits.cpu | default "1" }}
          {{- end }}
          {{- if .Values.dwbld.resources.requests }}
          requests:
            memory: {{ .Values.dwbld.resources.requests.memory | default "256Mi" }}
            cpu: {{ .Values.dwbld.resources.requests.cpu | default "0.5" }}
          {{- end }}
        {{- end }}
        volumeMounts:
        {{- include "volumeMounts.spk" . | nindent 8 }}
        - name: tls-dwbld-grpc-clt-volume
          mountPath: /tls/dwbld/grpc/clt/
          readOnly: true
        - name: tls-dwbld-grpc-svr-volume
          mountPath: /tls/dwbld/grpc/svr/
          readOnly: true
        {{- if .Values.dwbld.fluentbit_sidecar.enabled }}
        - name: f5-log-pipes
          mountPath: /var/run/f5
        {{- if .Values.dwbld.fluentbit_sidecar.fluentbit.tls.enabled }}
        - name: tls-dwbldfluentbit-grpc-clt-volume
          mountPath: /tls/dwbldfluentbit/grpc/clt/
        {{- end }}
        {{- end }}
        {{- if (eq .Values.global.platformType "robin") }}
        - mountPath: /var/crash
          name: f5-core-store
          readOnly: false
        {{- end }}  
        - name: f5tmstat
          mountPath: /var/tmstat 
        {{- if .Values.dwbld.f5_csm_qkview.enabled }}
        - name: tls-dwbldqkview-grpc-svr-volume
          mountPath: /tls/dwbldqkview/grpc/svr
          readOnly: true
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.dwbld.securityContext.allowPrivilegeEscalation }}
          privileged: {{ .Values.dwbld.securityContext.privileged }}
          runAsUser: {{ .Values.dwbld.securityContext.runAsUser }}
          runAsGroup: {{ .Values.dwbld.securityContext.runAsGroup }}
        env:
        - name: FLUENTBIT_ENABLED
          value: {{ if .Values.dwbld.fluentbit_sidecar.enabled }}"true"{{ else }}"false"{{ end }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GRPC_SRV_PORT
          value: "{{ .Values.dwbld.grpc.port | default "8750" }}"
        - name: GRPC_SRV_ENABLED
          value: "true"
        - name: GRPC_SRV_TLS
          value: "true"
        - name: GRPC_SRV_CA
          value: /tls/dwbld/grpc/svr/ca.crt
        - name: GRPC_SRV_CERT
          value: {{ .Values.dwbld.grpc.cert | default "grpc-svc.crt" }}
        - name: GRPC_SRV_KEY
          value: {{ .Values.dwbld.grpc.key | default "grpc-svc.key" }}
        - name: GRPC_CLIENT_CA
          value: /tls/dwbld/grpc/clt/ca.crt
        - name: GRPC_CLIENT_CERT
          value: {{ .Values.dwbld.grpc.client_cert | default "grpc-dwbld-client.crt" }}
        - name: GRPC_CLIENT_KEY
          value: {{ .Values.dwbld.grpc.client_key | default "grpc-dwbld-client.key" }}
        - name: GRPC_REMOTE_DNS
          value: {{ .Values.global.tmm.grpc.name }}
        - name: PATH_CERTS
          value: "/etc/ssl/certs"
        - name: PATH_KEYS
          value: "/etc/ssl/private"
        - name: LOG_LEVEL
          value: {{ if .Values.dwbld.debug }}"debug"{{ else }}{{ .Values.dwbld.log_level | default "notice" }}{{ end }}
        - name: CFG_DBG_ENABLED
          value: {{ if .Values.dwbld.debug }}"true"{{ else }}"false"{{ end }}
        - name: WRITE_BLOB_TO_FILE
          value: {{ if .Values.dwbld.debug }}"true"{{ else }}"false"{{ end }} 
        - name: MAX_BLOB_SIZE_MB
          value: {{ .Values.dwbld.blob.maxFwBlobSizeMb | default "512" | quote  }}
        - name: MAX_NAT_BLOB_SIZE_MB
          value: {{ .Values.dwbld.blob.maxNatBlobSizeMb | default "512" | quote }} 
        {{- if .Values.dwbld.fluentbit_sidecar.enabled }}
        - name: EXPORT_DWBLD_LOGS
          value: "true"
        {{- end }}
        - name: GRPC_BLOBD_PORT
          value: "{{ .Values.dwbld.blobd.grpc.port | default "" }}"
        {{- if .Values.dwbld.f5_csm_qkview.enabled }}
        - name: QK_GRPC_PORT
          value: "{{ .Values.dwbld.f5_csm_qkview.grpc_port }}"
        - name: QK_TLS_CA_BUNDLE
          value: "/etc/ssl/certs/ca-root-cert.pem"
        - name: QK_TLS_CERT_FILE
          value: "/etc/ssl/certs/server-cert.pem"
        - name: QK_TLS_KEY_FILE
          value: "/etc/ssl/certs/server-key.pem"
        - name: QK_TLS_CERT_RETRY_WAIT
          value: "5s"
        - name: CONTAINER_NAME
          value: "dwbldqkview"
        - name: USING_CERT_ORCHESTRATOR
          value: "true"
        {{- include "env.spk" (dict "cVersion" .Values.dwbld.image.tag ) | nindent 8}}
        {{- else }}
        {{- include "env.spk" (dict "cName" .Values.dwbld.name "cVersion" .Values.dwbld.image.tag ) | nindent 8}}
        {{- end }}
{{- if .Values.dwbld.fluentbit_sidecar.enabled }}
      - image: "{{ .Values.dwbld.fluentbit_sidecar.image.repository | required ".Values.dwbld.fluentbit_sidecar.image.repository is required." }}/{{ .Values.dwbld.fluentbit_sidecar.image.name }}:{{ .Values.dwbld.fluentbit_sidecar.image.tag }}"
        name: {{ .Values.dwbld.fluentbit_sidecar.name }}
        imagePullPolicy: {{ .Values.dwbld.fluentbit_sidecar.image.pullPolicy }}
        securityContext:
          readOnlyRootFilesystem: {{ .Values.dwbld.fluentbit_sidecar.securityContext.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: {{ .Values.dwbld.fluentbit_sidecar.securityContext.allowPrivilegeEscalation }}
          privileged: {{ .Values.dwbld.fluentbit_sidecar.securityContext.privileged }}
          runAsUser: {{ .Values.dwbld.fluentbit_sidecar.securityContext.runAsUser }}
          runAsGroup: {{ .Values.dwbld.fluentbit_sidecar.securityContext.runAsGroup }}
        stdin: true
        tty: true
        env:
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: POD
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: f5-log-pipes
            mountPath: /var/run/f5
            readOnly: true
          - name: f5-dwbld-fluentbit-config
            mountPath: /fluent-bit/etc/
          - mountPath: /tmp
            name: tmp
            subPath: fluentbit-tmp
          - mountPath: /run
            name: run
            subPath: fluentbit-run
          - mountPath: /logs
            name: logs
            subPath: fluentbit-logs
          - mountPath: /var/log
            name: var-log
            subPath: fluentbit-var-log
        {{- if .Values.dwbld.fluentbit_sidecar.fluentbit.tls.enabled }}
          - name: tls-dwbldfluentbit-grpc-clt-volume
            mountPath: /tls/dwbldfluentbit/grpc/clt/
        {{- end }}
{{- end }}
      volumes:
      {{- include "volumes.spk" . | nindent 6 }}
      {{- if (eq .Values.global.platformType "robin") }}
      - name: f5-core-store
        hostPath:
          path: /home/crash/f5
      {{- end }}
      - name: tls-dwbld-grpc-clt-volume
        secret:
          secretName: tls-dwbld-grpc-clt-secret
      - name: tls-dwbld-grpc-svr-volume
        secret:
          secretName: tls-dwbld-grpc-svr-secret
      - name: f5tmstat
        hostPath:
          path: /root/tmstat
      {{- if .Values.dwbld.fluentbit_sidecar.enabled }}
      - name: f5-log-pipes
        emptyDir: {}
      - name: f5-dwbld-fluentbit-config
        configMap:
          name: f5-dwbld-fluentbit-config
      {{- if .Values.dwbld.fluentbit_sidecar.fluentbit.tls.enabled }}
      - name: tls-dwbldfluentbit-grpc-clt-volume
        secret:
          secretName: tls-dwbldfluentbit-grpc-clt-secret
      {{- end }}
      {{- end }}
      {{- if .Values.dwbld.f5_csm_qkview.enabled }}
      - name: tls-dwbldqkview-grpc-svr-volume
        secret:
          secretName: tls-dwbldqkview-grpc-svr-secret
      {{- end }}
      - name: tmp
        emptyDir: {}
      - name: run
        emptyDir: {}
      - name: qkview
        emptyDir: {}
      - emptyDir: {}
        name: logs
      - emptyDir: {}
        name: var-log
{{- end }}
{{- end }}
