{{ $base_port := (.Values.dwbld.grpc.port | int )}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dwbld.grpc.name }}
  labels:
    app: {{ .Values.dwbld.name }}
    type: grpc
spec:
  selector:
    app: {{ .Values.dwbld.name }}
  ports:
    - protocol: TCP
      name: grpc-dwbld
      port: {{ $base_port }}
      targetPort: {{ $base_port }}
---
{{- if .Values.dwbld.f5_csm_qkview.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: f5-dwbld
  labels:
    app: {{ .Values.dwbld.name }}
spec:
  ports:
  - port: {{ .Values.dwbld.f5_csm_qkview.grpc_port }}
    name: grpc-port-qkview
    protocol: TCP
    targetPort: {{ .Values.dwbld.f5_csm_qkview.grpc_port }}
  selector:
    app: {{ .Values.dwbld.name }}
{{- end }}

