apiVersion: v2
appVersion: v1.127.13-0.0.5
dependencies:
- name: spk-common
  repository: ""
  version: 1.3.5
description: A Helm chart for f5-afm
name: f5-afm
type: application
version: 0.28.9-0.0.9
