{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cneproxy.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cneproxy.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "cneproxy.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cneproxy.name" . }}
        tenant-selector: {{ .Release.Name }}-tenant
        qkview-collect: {{ .Release.Name }}
    spec:
      {{- if .Values.f5cneproxy.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.f5cneproxy.nodeSelector | indent 8 }}
      {{- end }}
      serviceAccount: {{ include "cneproxy.saname" . }}
      hostNetwork: {{ .Values.f5cneproxy.hostNetwork }}
      containers:
        - name: {{ include "cneproxy.name" . }}
          image: "{{ .Values.f5cneproxy.image.repository }}{{if ne .Values.f5cneproxy.image.repository ""}}/{{end}}{{ .Values.f5cneproxy.image.name }}:{{ .Values.f5cneproxy.image.tag }}"
          imagePullPolicy: {{ .Values.f5cneproxy.image.pullPolicy }}
          {{- if .Values.f5cneproxy.resources }}
          resources:
            {{- if .Values.f5cneproxy.resources.limits }}
            limits:
              memory: {{ .Values.f5cneproxy.resources.limits.memory | default "512Mi" }}
              cpu: {{ .Values.f5cneproxy.resources.limits.cpu | default "1" }}
            {{- end }}
            {{- if .Values.f5cneproxy.resources.requests }}
            requests:
              memory: {{ .Values.f5cneproxy.resources.requests.memory | default "256Mi" }}
              cpu: {{ .Values.f5cneproxy.resources.requests.cpu | default "0.5" }}
            {{- end }}
          {{- end }}
          ports:
          - containerPort: 40001
            name: qkview-collect
            protocol: TCP
          volumeMounts:
          - name: pv-data
            subPath: f5-cne-proxy-certs
            mountPath: /tls/f5-cne-proxy/http/svr
          - mountPath: /backup
            name: pv-data
            subPath: f5-csm-backup
          - name: pv-data
            subPath: f5-cne-proxy-qkview
            mountPath: /tls/f5-cne-proxy/qkview
          - name: pv-data
            subPath: logs
            mountPath: /logs

          securityContext:
            allowPrivilegeEscalation: {{ .Values.f5cneproxy.securityContext.allowPrivilegeEscalation }}
            runAsUser: {{ .Values.f5cneproxy.securityContext.runAsUser }}
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CNE_PROXY_HTTP_PORT
            value: "{{ .Values.f5cneproxy.https.port }}"
          - name: VAULT_SSL_CERT_FILE
            value: /tls/f5-cne-proxy/http/svr/f5-cne-proxy-http-svr.pem
          - name: VAULT_SSL_KEY_FILE
            value: /tls/f5-cne-proxy/http/svr/f5-cne-proxy-http-svr-key.pem
          - name: VAULT_CA_FILE
            value: /tls/f5-cne-proxy/http/svr/ca.pem
          - name: VAULT_ROLE_NAME
            value: {{- include "common.tenantPrefix" . | indent 1 }}{{ .Values.f5cneproxy.vault.roleName }}
          - name: VAULT_PORT
            value: "{{ .Values.f5cneproxy.vault.port }}"
          - name: VAULT_HOST
            value: {{ .Values.f5cneproxy.vault.vaultHost }}
          - name: QK_TLS_CA_BUNDLE
            value: "/tls/f5-cne-proxy/qkview/ca.pem"
          - name: QK_TLS_CERT_FILE
            value: "/tls/f5-cne-proxy/qkview/f5-cne-proxy-qkview.pem"
          - name: QK_TLS_KEY_FILE
            value: "/tls/f5-cne-proxy/qkview/f5-cne-proxy-qkview-key.pem"
          - name: CONTAINER_NAME
            value: {{ include "cneproxy.name" . }}
          - name: F5_CONSOLE_LOGGING_ENABLED
            value: "true"
          {{- if .Values.global.enableReleaseConfig }}
          envFrom: 
            - configMapRef:
                name: {{ .Values.releaseConfig | default .Release.Name }}-configmap
          {{- end }}
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: data-store
            readOnly: false

{{- end }}
