{{- if and .Values.enabled .Values.f5cneproxy.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cneproxy.rbacname" . }}
rules:
- apiGroups:
  - 'k8s.f5net.com'
  resources:
  - 'f5-big-dns-apps'
  - 'f5-big-gslb-datacenters'
  - 'f5-big-gslb-monitors'
  - 'f5-big-gslb-pools'
  - 'f5-big-gslb-servers'
  - 'f5-big-gslb-wideips'
  - 'f5-big-gslb-instances'
  - 'f5-big-gslb-probe-agents'
  - 'f5-big-gslb-topology-groups'
  - 'f5-big-gslb-topology-records'
  - 'f5-big-gslb-optionses'
  - 'f5-big-gslb-prober-pools'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - 'configmaps'
  verbs:
  - '*'
- apiGroups:
  - 'apps'
  resources:
  - 'deployments'
  resourceNames:
  - 'f5-cne-proxy'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cneproxy.bindingname" . }}
roleRef:
  kind: Role
  name: {{ include "cneproxy.rbacname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "cneproxy.saname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
