apiVersion: v1
kind: ConfigMap
metadata:
  name: sensitive-config
data:
  # sensitive config fields
  F5BigGslbServer.spec.password: ""
  F5BigGslbMonitor.spec.http.password: ""
  F5BigGslbMonitor.spec.https.password: ""
immutable: true