# =============================================================================
# ROOT TERRAGRUNT CONFIGURATION
# AWS Full Stack: VPC → EKS → BNK Gateway API
#
# Generated by BNK-Forge
# Project: {{PROJECT_NAME}}
# Environment: {{ENVIRONMENT}}
# Platform: AWS
# =============================================================================

# -----------------------------------------------------------------------------
# LOCALS - Common Configuration
# -----------------------------------------------------------------------------
locals {
  # Project metadata
  project_name = "{{PROJECT_NAME}}"
  environment  = "{{ENVIRONMENT}}"
  aws_region   = "{{AWS_REGION}}"
  aws_profile  = "{{AWS_PROFILE}}"

  # Common tags applied to all AWS resources
  common_tags = {
    Project     = local.project_name
    Environment = local.environment
    ManagedBy   = "bnk-forge"
    Terraform   = "true"
  }

  # Kubernetes cluster name (used across all K8s modules)
  cluster_name = "${local.project_name}-${local.environment}-eks"
}

# -----------------------------------------------------------------------------
# REMOTE STATE CONFIGURATION (S3 Backend)
# -----------------------------------------------------------------------------
remote_state {
  backend = "s3"

  config = {
    bucket         = "{{S3_BUCKET_NAME}}"  # e.g., "my-terraform-state"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = local.aws_region
    encrypt        = true
    dynamodb_table = "{{DYNAMODB_TABLE}}"  # e.g., "terraform-lock"
    profile        = local.aws_profile
  }

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

# -----------------------------------------------------------------------------
# TERRAFORM CONFIGURATION
# -----------------------------------------------------------------------------
terraform {
  source = "${get_repo_root()}//{{MODULE_PATH}}"
}

# -----------------------------------------------------------------------------
# AWS PROVIDER CONFIGURATION
# -----------------------------------------------------------------------------
generate "provider_aws" {
  path      = "provider_aws.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "aws" {
  region  = "${local.aws_region}"
  profile = "${local.aws_profile}"

  default_tags {
    tags = ${jsonencode(local.common_tags)}
  }
}
EOF
}

# -----------------------------------------------------------------------------
# KUBERNETES PROVIDER CONFIGURATION (for K8s and BNK modules)
# -----------------------------------------------------------------------------
generate "provider_kubernetes" {
  path      = "provider_kubernetes.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
data "aws_eks_cluster" "cluster" {
  name = dependency.eks.outputs.cluster_name
}

data "aws_eks_cluster_auth" "cluster" {
  name = dependency.eks.outputs.cluster_name
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}
EOF
}

# -----------------------------------------------------------------------------
# HELM PROVIDER CONFIGURATION (for BNK Helm charts)
# -----------------------------------------------------------------------------
generate "provider_helm" {
  path      = "provider_helm.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
    token                  = data.aws_eks_cluster_auth.cluster.token
  }

  # For F5 OCI registry authentication
  registry_config_path = pathexpand("~/.config/helm/registry/config.json")
}
EOF
}

# =============================================================================
# MODULE DEPENDENCIES
# =============================================================================

# -----------------------------------------------------------------------------
# INFRASTRUCTURE LAYER
# -----------------------------------------------------------------------------

# VPC Module
dependency "vpc" {
  config_path = "../infra/aws/vpc"

  mock_outputs = {
    vpc_id                        = "vpc-mock"
    vpc_cidr_block                = "10.0.0.0/16"
    public_subnet_id              = "subnet-mock-public"
    private_external_subnet_ids   = ["subnet-mock-ext-1", "subnet-mock-ext-2"]
    private_internal_subnet_ids   = ["subnet-mock-int-1", "subnet-mock-int-2"]
    availability_zones            = ["us-west-2a", "us-west-2b"]
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# Security Module
dependency "security" {
  config_path = "../infra/aws/security"

  mock_outputs = {
    vpc_security_group_id     = "sg-mock"
    infrastructure_key_name   = "mock-key"
    eks_cluster_role_arn      = "arn:aws:iam::123456789012:role/mock-eks-cluster"
    nodegroup_role_arn        = "arn:aws:iam::123456789012:role/mock-nodegroup"
    jumphost_public_ip        = "1.2.3.4"
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# EKS Cluster Module
dependency "eks" {
  config_path = "../infra/aws/eks"

  mock_outputs = {
    cluster_name                      = "mock-cluster"
    cluster_endpoint                  = "https://mock-endpoint.eks.amazonaws.com"
    cluster_certificate_authority_data = "LS0tLS1..."
    oidc_provider_arn                 = "arn:aws:iam::123456789012:oidc-provider/mock"
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# Storage Module
dependency "storage" {
  config_path = "../infra/aws/storage"

  mock_outputs = {
    storage_classes_deployed = 3
    storage_class_names      = ["gp3-standard", "gp3-fast", "efs-sc"]
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# -----------------------------------------------------------------------------
# BNK FOUNDATION LAYER
# -----------------------------------------------------------------------------

# FAR Setup Module
dependency "far_setup" {
  config_path = "../bnk/far-setup"

  mock_outputs = {
    spk_namespace         = "f5-spk"
    utils_namespace       = "f5-utils"
    far_secret_name       = "far-secret"
    cert_manager_version  = "1.13.0"
    setup_complete        = true
    component_versions    = {}
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# -----------------------------------------------------------------------------
# KUBERNETES LAYER
# -----------------------------------------------------------------------------

# Cert-Manager Module
dependency "cert_manager" {
  config_path = "../k8s/cert-manager"

  mock_outputs = {
    cert_manager_ready = true
    release_status     = "deployed"
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# Network Setup Module (Optional - only if using network attachments)
dependency "network_setup" {
  config_path = "../k8s/network-setup"

  skip = {{SKIP_NETWORK_SETUP}}  # Set to true if not using F5 network attachments

  mock_outputs = {
    external_nad_name = "external-nad"
    internal_nad_name = "internal-nad"
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# -----------------------------------------------------------------------------
# BNK PLATFORM LAYER
# -----------------------------------------------------------------------------

# FLO (F5 Lifecycle Operator) Module
dependency "flo" {
  config_path = "../bnk/flo"

  mock_outputs = {
    flo_ready        = true
    flo_namespace    = "f5-spk"
    crds_installed   = true
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# -----------------------------------------------------------------------------
# BNK GATEWAY API LAYER
# -----------------------------------------------------------------------------

# BNK GatewayClass Module
dependency "bnk_gatewayclass" {
  config_path = "../bnk/bnk-gatewayclass"

  mock_outputs = {
    gatewayclass_name  = "f5-gateway-class"
    gatewayclass_ready = true
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# Gateway Module
dependency "gateway" {
  config_path = "../bnk/gateway"

  mock_outputs = {
    gateway_name      = "f5-gateway"
    gateway_ready     = true
    gateway_addresses = ["10.0.10.100"]
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# =============================================================================
# MODULE INPUTS
# These inputs are automatically populated from dependencies and variables
# =============================================================================

inputs = {
  # Common inputs
  project_name = local.project_name
  environment  = local.environment
  aws_region   = local.aws_region
  aws_profile  = local.aws_profile
  common_tags  = local.common_tags
  cluster_name = local.cluster_name

  # Module-specific inputs will be added here based on selected module
  # Examples:
  # vpc_id = dependency.vpc.outputs.vpc_id
  # cluster_endpoint = dependency.eks.outputs.cluster_endpoint
  # flo_ready = dependency.flo.outputs.flo_ready
}

# =============================================================================
# NOTES FOR DEPLOYMENT
# =============================================================================
#
# 1. Initialize modules in order:
#    terragrunt run-all init --terragrunt-working-dir infra/aws
#    terragrunt run-all init --terragrunt-working-dir k8s
#    terragrunt run-all init --terragrunt-working-dir bnk
#
# 2. Plan deployment:
#    terragrunt run-all plan --terragrunt-working-dir .
#
# 3. Apply in layers:
#    terragrunt run-all apply --terragrunt-working-dir infra/aws
#    terragrunt run-all apply --terragrunt-working-dir k8s
#    terragrunt run-all apply --terragrunt-working-dir bnk
#
# 4. Destroy (reverse order):
#    terragrunt run-all destroy --terragrunt-working-dir bnk
#    terragrunt run-all destroy --terragrunt-working-dir k8s
#    terragrunt run-all destroy --terragrunt-working-dir infra/aws
#
# =============================================================================
