# =============================================================================
# ROOT TERRAGRUNT CONFIGURATION
# Existing Kubernetes → BNK Gateway API
#
# Generated by BNK-Forge
# Project: {{PROJECT_NAME}}
# Environment: {{ENVIRONMENT}}
# Platform: {{KUBERNETES_PLATFORM}}  # EKS, AKS, GKE, on-prem, etc.
# =============================================================================

# -----------------------------------------------------------------------------
# LOCALS - Common Configuration
# -----------------------------------------------------------------------------
locals {
  # Project metadata
  project_name = "{{PROJECT_NAME}}"
  environment  = "{{ENVIRONMENT}}"

  # Kubernetes configuration
  cluster_name        = "{{CLUSTER_NAME}}"  # Your existing cluster name
  kubeconfig_path     = "{{KUBECONFIG_PATH}}"  # Path to kubeconfig, default: ~/.kube/config
  kubeconfig_context  = "{{KUBECONFIG_CONTEXT}}"  # Optional: specific context to use

  # Common labels applied to all Kubernetes resources
  common_labels = {
    project     = local.project_name
    environment = local.environment
    managed-by  = "bnk-forge"
    terraform   = "true"
  }
}

# -----------------------------------------------------------------------------
# REMOTE STATE CONFIGURATION
# For on-prem/existing K8s: Use local or Consul backend
# -----------------------------------------------------------------------------
remote_state {
  backend = "{{BACKEND_TYPE}}"  # local, consul, http, etc.

  config = {
    {{#if BACKEND_TYPE == "local"}}
    path = "${get_repo_root()}/terraform.tfstate.d/${path_relative_to_include()}/terraform.tfstate"
    {{/if}}
    {{#if BACKEND_TYPE == "consul"}}
    address = "{{CONSUL_ADDRESS}}"
    path    = "${local.project_name}/${path_relative_to_include()}/terraform.tfstate"
    scheme  = "https"
    {{/if}}
    {{#if BACKEND_TYPE == "s3"}}
    # If using AWS S3 for non-EKS cluster
    bucket         = "{{S3_BUCKET_NAME}}"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "{{AWS_REGION}}"
    encrypt        = true
    dynamodb_table = "{{DYNAMODB_TABLE}}"
    {{/if}}
  }

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

# -----------------------------------------------------------------------------
# TERRAFORM CONFIGURATION
# -----------------------------------------------------------------------------
terraform {
  source = "${get_repo_root()}//{{MODULE_PATH}}"
}

# -----------------------------------------------------------------------------
# KUBERNETES PROVIDER CONFIGURATION
# Uses existing kubeconfig - works with any Kubernetes
# -----------------------------------------------------------------------------
generate "provider_kubernetes" {
  path      = "provider_kubernetes.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "kubernetes" {
  config_path    = "${local.kubeconfig_path}"
  {{#if KUBECONFIG_CONTEXT}}
  config_context = "${local.kubeconfig_context}"
  {{/if}}
}
EOF
}

# -----------------------------------------------------------------------------
# HELM PROVIDER CONFIGURATION
# Uses existing kubeconfig - works with any Kubernetes
# -----------------------------------------------------------------------------
generate "provider_helm" {
  path      = "provider_helm.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "helm" {
  kubernetes {
    config_path    = "${local.kubeconfig_path}"
    {{#if KUBECONFIG_CONTEXT}}
    config_context = "${local.kubeconfig_context}"
    {{/if}}
  }

  # For F5 OCI registry authentication
  registry_config_path = pathexpand("~/.config/helm/registry/config.json")
}
EOF
}

# =============================================================================
# MODULE DEPENDENCIES
# =============================================================================

# -----------------------------------------------------------------------------
# BNK FOUNDATION LAYER
# -----------------------------------------------------------------------------

# FAR Setup Module - REQUIRED FIRST
dependency "far_setup" {
  config_path = "../bnk/far-setup"

  mock_outputs = {
    spk_namespace         = "f5-spk"
    utils_namespace       = "f5-utils"
    far_secret_name       = "far-secret"
    cert_manager_version  = "1.13.0"
    setup_complete        = true
    component_versions    = {}
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# -----------------------------------------------------------------------------
# KUBERNETES LAYER
# -----------------------------------------------------------------------------

# Cert-Manager Module - RECOMMENDED
dependency "cert_manager" {
  config_path = "../k8s/cert-manager"

  mock_outputs = {
    cert_manager_ready = true
    release_status     = "deployed"
    namespace          = "f5-utils"
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# Network Setup Module - OPTIONAL (only if using F5 network attachments)
dependency "network_setup" {
  config_path = "../k8s/network-setup"

  skip = {{SKIP_NETWORK_SETUP}}  # Set to true if not needed

  mock_outputs = {
    external_nad_name = "external-nad"
    internal_nad_name = "internal-nad"
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# -----------------------------------------------------------------------------
# BNK PLATFORM LAYER
# -----------------------------------------------------------------------------

# FLO (F5 Lifecycle Operator) Module - REQUIRED
dependency "flo" {
  config_path = "../bnk/flo"

  mock_outputs = {
    flo_ready        = true
    flo_namespace    = "f5-spk"
    crds_installed   = true
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# DSSM Module - OPTIONAL (only for legacy SPK controller mode)
dependency "dssm" {
  config_path = "../bnk/dssm"

  skip = {{SKIP_DSSM}}  # Set to true if using Gateway API mode only

  mock_outputs = {
    dssm_ready             = true
    sentinel_service_host  = "dssm-sentinel.f5-utils.svc.cluster.local"
    sentinel_service_port  = 26379
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# Fluentd Module - OPTIONAL (for logging)
dependency "fluentd" {
  config_path = "../bnk/fluentd"

  skip = {{SKIP_FLUENTD}}  # Set to true if not using F5 logging

  mock_outputs = {
    fluentd_ready        = true
    fluentd_service_host = "fluentd.f5-utils.svc.cluster.local"
    fluentd_service_port = 54321
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# -----------------------------------------------------------------------------
# BNK GATEWAY API LAYER
# -----------------------------------------------------------------------------

# BNK GatewayClass Module - REQUIRED for Gateway API
dependency "bnk_gatewayclass" {
  config_path = "../bnk/bnk-gatewayclass"

  mock_outputs = {
    gatewayclass_name  = "f5-gateway-class"
    gatewayclass_ready = true
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# Gateway Module - REQUIRED for Gateway API
dependency "gateway" {
  config_path = "../bnk/gateway"

  mock_outputs = {
    gateway_name      = "f5-gateway"
    gateway_ready     = true
    gateway_addresses = ["10.0.10.100"]
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# Routes Module - REQUIRED for traffic routing
dependency "routes" {
  config_path = "../bnk/routes"

  mock_outputs = {
    route_ready = true
    route_name  = "app-route"
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# -----------------------------------------------------------------------------
# BNK POLICY LAYER (OPTIONAL)
# -----------------------------------------------------------------------------

# Security Policy Module - OPTIONAL
dependency "bnk_secpolicy" {
  config_path = "../bnk/bnk-secpolicy"

  skip = {{SKIP_SECPOLICY}}  # Set to true if not using security policies

  mock_outputs = {
    policy_ready = true
    policy_name  = "security-policy"
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# Network Policy Module - OPTIONAL
dependency "bnk_netpolicy" {
  config_path = "../bnk/bnk-netpolicy"

  skip = {{SKIP_NETPOLICY}}  # Set to true if not using network policies

  mock_outputs = {
    policy_ready = true
    policy_name  = "network-policy"
  }

  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

# =============================================================================
# MODULE INPUTS
# These inputs are automatically populated from dependencies and variables
# =============================================================================

inputs = {
  # Common inputs
  project_name   = local.project_name
  environment    = local.environment
  cluster_name   = local.cluster_name
  common_labels  = local.common_labels

  # Module-specific inputs will be added here based on selected module
  # Examples:
  # flo_namespace = dependency.far_setup.outputs.spk_namespace
  # flo_ready = dependency.flo.outputs.flo_ready
  # gatewayclass_name = dependency.bnk_gatewayclass.outputs.gatewayclass_name
}

# =============================================================================
# DEPLOYMENT NOTES
# =============================================================================
#
# PREREQUISITES:
# 1. Ensure kubectl is configured and can access your cluster:
#    kubectl get nodes
#
# 2. Verify you have F5 FAR credentials file:
#    ls -la ~/path/to/far-service-account.json
#
# 3. Authenticate with F5 registry:
#    helm registry login repo.f5.com --username <service-account>
#
# DEPLOYMENT ORDER:
# 1. BNK Foundation:
#    terragrunt apply --terragrunt-working-dir bnk/far-setup
#
# 2. Kubernetes Layer:
#    terragrunt apply --terragrunt-working-dir k8s/cert-manager
#
# 3. BNK Platform:
#    terragrunt apply --terragrunt-working-dir bnk/flo
#
# 4. BNK Gateway API:
#    terragrunt apply --terragrunt-working-dir bnk/bnk-gatewayclass
#    terragrunt apply --terragrunt-working-dir bnk/gateway
#    terragrunt apply --terragrunt-working-dir bnk/routes
#
# 5. Verify deployment:
#    kubectl get gatewayclass
#    kubectl get gateway -n <namespace>
#    kubectl get httproute -n <namespace>
#
# =============================================================================
