
    
enabled: false
f5cneproxy: 
    name: f5-cne-proxy
    
    serviceAccount:
        create: true
    
    service:
        port: 8095

    nodeSelector: {}

    hostNetwork: false

    https:
        port: 8095

    securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 7053
    
    resources:
        limits:
            cpu: "1"
            memory: "512Mi"
        requests:
            cpu: "0.5"
            memory: "256Mi"

    image:
        name: f5-cne-proxy
        tag: v0.6.19
        pullPolicy: IfNotPresent

    rbac:
        create: true

    vault:
        roleName: f5-cne-proxy-http-svr
        port: 8200
        vaultHost: f5-eesv-vault