{{- define "spk-common.fluentbit-cm" -}}
{{- $scope := .fluentbit -}}
{{- $cmname := $scope.name -}}
{{ if .Values }}
{{- $scope = .Values.fluentbit -}}
{{- $cmname = .Chart.Name -}}
{{- end }}
{{- with $scope }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cmname }}-fluentbit-config
data:
  fluent-bit.conf: |-
    @INCLUDE main.conf
    @INCLUDE custom.conf
  main.conf: |-
  {{- with .mainFile }}
  {{- tpl . $ | nindent 4 }}
  {{- end }}
  {{- with .mainAddFiles }}
  {{- tpl . $ | nindent 2 }}
  {{- end }}
  custom.conf: |-
  {{- with .customFile }}
  {{- tpl . $ | nindent 4 }}
  {{- end }}
  {{- with .customAddFiles }}
  {{- tpl . $ | nindent 2 }}
  {{- end }}

{{- end }}
{{- end }}
