

logLevel: "info"

image:
  name: f5-analyzer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.0.3-0.0.5

# defined here assuming this will be common for all images under f5ingress
imageCredentials:
  name: f5ingress-regsecret

nameOverride: ""
fullnameOverride: ""

pod:
  annotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits: {}
  #  cpu: 100m
  #  memory: 128Mi
  requests: {}
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  certmgr:
    external: false
    ## If using an external cert-manager installation, the issuerRef must be populated with the required fields. Please refer to cert-manager CRD schema.
    # issuerRef:
    #   name: cert-issuer
    #   kind: Issuer
    #   group: cert-manager.io

analyzer:
  name: f5-analyzer
  enabled: false
  grpc:
    port: 8751
  serviceAccount:
    create: true
