{{- if (not (index .Values "f5-tmm").tmm.Only) }}
{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "f5ingress.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "f5ingress.labels" . | nindent 4 }}
{{- if .Values.controller.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.controller.serviceAccount.imagePullSecrets }}
{{- end }}
{{- end }}
{{- end }}
