---
{{ $controller_grpc_port := (.Values.controller.f5_csm_qkview.grpc.port | int )}}
{{ $lic_grpc_port := (.Values.controller.f5_lic_helper.f5_csm_qkview.grpc_port | int )}}
{{ $crdupdater := (.Values.controller.crdupdater.f5_csm_qkview.grpc_port | int )}}
{{ $tmm_pod_manager := (.Values.controller.tmm_pod_manager.f5_csm_qkview.grpc_port | int )}}
apiVersion: v1
kind: Service
metadata:
  {{- if (eq .Values.global.platformType "mbip-ve") }}
  name: {{ include "f5ingress.name" . }}
  labels:
    app: {{ include "f5ingress.name" . }}
    type: grpc
  {{- else }}
  name: {{ include "f5ingress.appName" . }}
  labels:
    app: {{ include "f5ingress.appName" . }}
    type: grpc
  {{- end }}
spec:
  selector:
  {{- if (eq .Values.global.platformType "mbip-ve") }}
    app: {{ include "f5ingress.appName" . }}
  {{- else }}
    app: {{ include "f5ingress.name" . }}
  {{- end }}
  clusterIP: "None"
  ports:
  {{- if .Values.controller.f5_csm_qkview.enabled }}
    - protocol: TCP
      name: controller-grpc-port
      port: {{ $controller_grpc_port }}
      targetPort: {{ $controller_grpc_port }}
  {{- end }}
  {{- if .Values.controller.f5_lic_helper.enabled }}
    - protocol: TCP
      name: lic-grpc-port
      port: {{ $lic_grpc_port }}
      targetPort: {{ $lic_grpc_port }}
  {{- end }}
  {{- if .Values.controller.crdupdater.enabled }}
    - protocol: TCP
      name: crdupdater-grpc-port
      port: {{ $crdupdater }}
      targetPort: {{ $crdupdater }}
  {{- end }}
  {{- if .Values.controller.tmm_pod_manager.enabled }}
    - protocol: TCP
      name: tmm-pod-manager-grpc-port
      port: {{ $tmm_pod_manager }}
      targetPort: {{ $tmm_pod_manager }}
  {{- end }}
