# Check if the UDP settings CRD is present in the cluster.
{{- if (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "f5-big-udp-settings.k8s.f5net.com") }}

apiVersion: k8s.f5net.com/v1
kind: F5BigUdpSetting
metadata:
  name: sys-default-dns-udp
spec:
  allowNoPayload: false
  bufferMaxBytes: 655350
  bufferMaxPackets: 0
  datagramLoadBalancing: true
  idleTimeout: 5
  ipDFMode: "pmtu"
  ipTOSToClient: 0
  ipTTLMode: "proxy"
  ipTTLV4: 255
  ipTTLV6: 64
  linkQOSToClient: 0
  noChecksum: false
  proxyMSS: false
  sendBufferSize: 655350

{{- end }}
