{{- if and .Values.dnsx.enabled (index .Values "f5-tmm").enabled (index .Values "f5-tmm").tmm.grpc.enabled }}
{{ $port := (.Values.dnsx.grpc.port | int )}}
{{ $qport := (.Values.dnsx.f5_csm_qkview.grpc_port | int )}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dnsx.grpc.name }}
  labels:
    app: {{ .Values.dnsx.name }}
    type: grpc
spec:
  selector:
    app: {{ .Values.dnsx.name }}
  ports:
    - protocol: TCP
      name: grpc-dnsx
      port: {{ $port }}
      targetPort: {{ $port }}
{{- if .Values.dnsx.f5_csm_qkview.enabled }}
{{ $qport := (.Values.dnsx.f5_csm_qkview.grpc_port | int )}}
---
apiVersion: v1
kind: Service
metadata:
  name: f5-zxfrd
  labels:
    app: {{ .Values.dnsx.name }}
spec:
  ports:
  - port: {{ $qport }}
    name: qkview-grpc-dnsx
    protocol: TCP
    targetPort: {{ $qport }}
  selector:
    app: {{ .Values.dnsx.name }}
{{- end }}
{{- end }}
