{{- if and .Values.dnsx.enabled .Values.dnsx.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dnsx.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
{{- end }}

