{{- if not .Values.controller.Only }}
{{- if and .Values.dnsx.enabled .Values.dnsx.config.entries}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dnsx.config.name }}
  namespace: {{ .Release.Namespace }}
data:
{{ toYaml .Values.dnsx.config.entries | indent 2 }}
{{- end }}
{{- end }}
