{{- if not .Values.controller.Only }}
{{- if .Values.gslbProbeAgent.enabled }}
{{- $release := $.Release.Name -}}
{{- $namespace := $.Release.Namespace -}}
{{- $metadataName := printf "%s-%s" $release (sha1sum $namespace) -}}
{{- $dataplaneVlanName := printf "%s-%s" "dp-ep" (sha1sum $namespace) | trunc 15 -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gslbProbeAgent.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.gslbProbeAgent.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.gslbProbeAgent.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.gslbProbeAgent.name }}
      {{- if .Values.gslbProbeAgent.annotations }}
      annotations:
{{ toYaml .Values.gslbProbeAgent.annotations | indent 8 }}
      {{- end }}
      {{- if and (index .Values "f5-tmm").enabled (index .Values "f5-tmm").tmm.cniNetworks }}
      {{- if eq (index .Values "f5-tmm").tmm.robinNetworks "true"}}
        robin.io/networks: {{ toYaml (index .Values "f5-tmm").tmm.cniNetworks }}
      {{- else }}
        k8s.v1.cni.cncf.io/networks: "{{ (index .Values "f5-tmm").tmm.cniNetworks }}"
      {{- end }}
      {{- end }}
    spec:
      hostname: {{ .Values.gslbProbeAgent.name }}
      subdomain: {{ .Values.gslbProbeAgent.grpc.name }}
      {{- if .Values.gslbProbeAgent.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.gslbProbeAgent.nodeSelector | indent 8 }}
      {{- end }}
      {{- if and .Values.imageCredentials .Values.imageCredentials.name }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
      {{- else }}
      imagePullSecrets: []
      {{- end }}
      containers:
      - image: "{{ .Values.gslbProbeAgent.image.repository }}/{{ .Values.gslbProbeAgent.image.name }}:{{ .Values.gslbProbeAgent.image.tag }}"
        name: {{ .Values.gslbProbeAgent.name }}
        imagePullPolicy: {{ .Values.gslbProbeAgent.image.pullPolicy }}
        {{- if not .Values.gslbProbeAgent.start }}
        command: ["tail", "-f", "/dev/null"]
        {{- end }}
        {{- if.Values.gslbProbeAgent.f5_csm_qkview.enabled }}
        ports:
        - name: qk-grpc-port
          containerPort: {{ .Values.gslbProbeAgent.f5_csm_qkview.grpc_port | int }}
          protocol: TCP
        {{- end }}
        {{- if .Values.gslbProbeAgent.securityContext }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
          privileged: {{ .Values.gslbProbeAgent.securityContext.privileged }}
          {{- if .Values.gslbProbeAgent.securityContext.runAsUser }}
          runAsUser: {{ .Values.gslbProbeAgent.securityContext.runAsUser }}
          {{- end }}
          {{- if .Values.gslbProbeAgent.securityContext.runAsGroup }}
          runAsGroup: {{ .Values.gslbProbeAgent.securityContext.runAsGroup }}
          {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.gslbProbeAgent.resources | nindent 10 }}
        volumeMounts:
        {{- include "volumeMounts.spk" . | nindent 8 }}
        - name: vol-mount-tmp
          mountPath: /tmp
          readOnly: false
        - name: vol-mount-run
          mountPath: /var/run
          readOnly: false
        - name: vol-mount-f5docker
          mountPath: /home/f5docker/.ssh
          readOnly: false
        {{- if.Values.gslbProbeAgent.f5_csm_qkview.enabled }}
        - name: tls-qkview-probeagent-grpc-svr-volume
          mountPath: /tls/qkview-probeagent/grpc/svr
          readOnly: true
        {{- end }}
        - name: tls-probeagent-grpc-svr-volume
          mountPath: /tls/probeagent/grpc/svr
          readOnly: true
        {{- if .Values.gslbProbeAgent.fluentbit_sidecar.enabled }}
        - name: f5-log-pipes
          mountPath: /var/log/f5
          readOnly: false
        {{- end }}
        env:
        - name: GRPC_PORT
          value: "{{ .Values.gslbProbeAgent.grpc.port }}"
        {{- include "env.spk" (dict "cName" .Values.gslbProbeAgent.name "cVersion" .Values.gslbProbeAgent.image.tag ) | nindent 8 }}
        {{- if.Values.gslbProbeAgent.f5_csm_qkview.enabled }}
        - name: QK_GRPC_PORT
          value: "{{ .Values.gslbProbeAgent.f5_csm_qkview.grpc_port }}"
        - name: QK_TLS_CA_BUNDLE
          value: /tls/qkview-probeagent/grpc/svr/ca.crt
        - name: QK_TLS_CERT_FILE
          value: /tls/qkview-probeagent/grpc/svr/tls.crt
        - name: QK_TLS_KEY_FILE
          value: /tls/qkview-probeagent/grpc/svr/tls.key
        - name: QK_TLS_CERT_RETRY_WAIT
          value: "5s"
        - name: SPK_QKVIEW_ENABLED
          value: "{{ .Values.gslbProbeAgent.f5_csm_qkview.enabled }}"
        {{- end }} # if.Values.f5_csm_qkview.enabled
        - name: KUBERNETES_SERVICE_NETWORK
          value: "{{ .Values.gslbProbeAgent.kubernetes_service_network }}"
        - name: GRPC_CERT_PATH
          value: /tls/probeagent/grpc/svr/tls.crt
        - name: GRPC_KEY_PATH
          value: /tls/probeagent/grpc/svr/tls.key
        - name: GRPC_CA_ROOT_PATH
          value: /tls/probeagent/grpc/svr/ca.crt
        - name: EXPORT_TELEMETRY
          value: {{ if .Values.gslbProbeAgent.fluentbit_sidecar.enabled }}"true"{{ else }}"false"{{ end }}
        - name: GSLB_PROBE_AGENT_LOG_LEVEL
          value: {{ .Values.gslbProbeAgent.logLevel }}
        - name: PROBE_LOG_LEVEL
          value: {{ .Values.gslbProbeAgent.probe.logLevel }}
{{ if .Values.gslbProbeAgent.customEnvVars }}
{{ toYaml .Values.gslbProbeAgent.customEnvVars | indent 8 }}
{{ end }}
        {{- if .Values.gslbProbeAgent.k8sprobes.enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.gslbProbeAgent.grpc.port }}
          initialDelaySeconds: 5
          periodSeconds: 1
        livenessProbe:
          tcpSocket:
            port: {{ .Values.gslbProbeAgent.grpc.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 16
          failureThreshold: 3
        {{- end }}
      {{- if .Values.gslbProbeAgent.fluentbit_sidecar.enabled }}
      - image: "{{ .Values.gslbProbeAgent.fluentbit_sidecar.image.repository }}/{{ .Values.gslbProbeAgent.fluentbit_sidecar.image.name }}:{{ .Values.gslbProbeAgent.fluentbit_sidecar.image.tag }}"
        name: {{ .Values.gslbProbeAgent.fluentbit_sidecar.name }}
        imagePullPolicy: {{ .Values.gslbProbeAgent.fluentbit_sidecar.image.pullPolicy }}
        {{- if .Values.gslbProbeAgent.securityContext }}
        securityContext:
          readOnlyRootFilesystem: true
          privileged: {{ .Values.gslbProbeAgent.securityContext.privileged }}
          {{- if .Values.gslbProbeAgent.securityContext.runAsUser }}
          runAsUser: {{ .Values.gslbProbeAgent.securityContext.runAsUser }}
          {{- end }}
        {{- end }}
        stdin: true
        tty: true
        env: {{- toYaml .Values.gslbProbeAgent.fluentbit_sidecar.env | nindent 12 }}
        volumeMounts:
        - name: vol-mount-tmp
          mountPath: /tmp
          readOnly: false
        - name: vol-mount-run
          mountPath: /var/run
          readOnly: false
        - name: f5-log-pipes
          mountPath: /var/log/f5
          readOnly: false
        {{- if .Values.gslbProbeAgent.fluentbit_sidecar.fluentbit.tls.enabled }}
        {{- toYaml .Values.gslbProbeAgent.fluentbit_sidecar.volumeMountsTls | nindent 8 }}
        {{- end}}
      {{- end }}
      volumes:
      {{- include "volumes.spk" . | nindent 6 }}
      - name: vol-mount-tmp
        emptyDir: {}
      - name: vol-mount-run
        emptyDir: {}
      - name: vol-mount-f5docker
        emptyDir: {}
      - name: tls-probeagent-grpc-svr-volume
        secret:
          secretName: tls-probeagent-grpc-svr-secret
      {{- if .Values.gslbProbeAgent.f5_csm_qkview.enabled }}
      - name: tls-qkview-probeagent-grpc-svr-volume
        secret:
          secretName: tls-qkview-probeagent-grpc-svr-secret
      {{- end }}
      {{- if .Values.gslbProbeAgent.fluentbit_sidecar.enabled }}
      - name: f5-log-pipes
        emptyDir: {}
      - name: f5-gslb-probe-agent-fluentbit-config
        configMap:
          name: f5-gslb-probe-agent-fluentbit-config
      {{- if .Values.gslbProbeAgent.fluentbit_sidecar.fluentbit.tls.enabled }}
      - name: f5-gslb-probe-agent-fluentbit-secrets
        secret:
          secretName: f5-toda-fluentbit-secret
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
