{{- if .Values.controller.tmm_pod_manager.enabled }}
{{ $base_port := (.Values.controller.tmm_pod_manager.grpc.port | int )}}
{{ $svc_name := .Values.controller.tmm_pod_manager.grpc.name }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $svc_name }}
  labels:
    app: {{ include "f5ingress.appName" . }}
    type: grpc
spec:
  selector:
    app: {{ include "f5ingress.appName" . }}
  ports:
    - protocol: TCP
      name: grpc-pod-mgr
      port: {{ $base_port }}
      targetPort: {{ $base_port }}
{{- end }}
---
{{- if (eq .Values.global.platformType "mbip-ve") }}
{{- if .Values.controller.tmm_pod_manager.f5_csm_qkview.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.controller.tmm_pod_manager.name }}
  labels:
    app: {{ include "f5ingress.appName" . }}
spec:
  selector:
    app: {{ include "f5ingress.appName" . }}
  ports:
    {{ $qkview_port_tpm := (.Values.controller.tmm_pod_manager.f5_csm_qkview.grpc_port | int)}}
    - protocol: TCP
      name: qkview-collect
      port: {{ $qkview_port_tpm }}
      targetPort: {{ $qkview_port_tpm }}
{{- end }}
{{- end }}