# Adding this as a pre-delete hook, would ensure that the webhook config gets modified such that the match rules are removed
# This will ensure uninstall will not give errors
{{ $base_port := (.Values.controller.validationService.port | int )}}
{{- $validationSvcCABundle := randAlphaNum 32 }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "certs-secret") }}
{{- if $secret }}
{{- $validationSvcCABundle = index $secret.data "ca_root.crt" }}
{{- end -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: f5validate-{{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-delete"
webhooks:
  - name: f5validate.f5net.com
{{- if semverCompare ">=1.21" .Capabilities.KubeVersion.Version }}
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        {{- if eq (include "f5ingress.watchAllNamespaces" .) "true" }}
        values: [{{ .Release.Namespace }}, ""]
        {{- else }}
        values: [{{ .Release.Namespace }},{{ include "f5ingress.watchNamespaceString" . }}]
        {{- end}}
{{- else }}
    failurePolicy: Ignore
{{- end }}
    clientConfig:
      service:
        name: f5-validation-svc
        port: {{ $base_port }}
        namespace: {{ .Release.Namespace }}
        path: "/f5-validator"
      caBundle: {{ $validationSvcCABundle }}
    sideEffects: None
    admissionReviewVersions: ["v1"]
