{{ $base_port := (.Values.controller.validationService.port | int )}}
{{- $validationSvcCABundle := randAlphaNum 32 }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "certs-secret") }}
{{- if $secret }}
{{- $validationSvcCABundle = index $secret.data "ca_root.crt" }}
{{- end -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: f5validate-{{ .Release.Namespace }}
  annotations:
    {{- if .Values.global.certmgr.external }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/tls-f5ingress-webhookvalidating-svr
    {{- else }}
    cm.f5co.k8s.f5net.com/inject-ca-from: {{ .Release.Namespace }}/tls-f5ingress-webhookvalidating-svr
    {{- end }}
webhooks:
  - name: f5validate.f5net.com
{{- if semverCompare ">=1.21" .Capabilities.KubeVersion.Version }}
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        {{- if eq (include "f5ingress.watchAllNamespaces" .) "true" }}
        values: [{{ .Release.Namespace }}, ""]
        {{- else }}
        values: [{{ .Release.Namespace }},{{ include "f5ingress.watchNamespaceString" . }}]
        {{- end }}
{{- else }}
    failurePolicy: Ignore
{{- end }}
    clientConfig:
      service:
        name: f5-validation-svc
        port: {{ $base_port }}
        namespace: {{ .Release.Namespace }}
        path: "/f5-validator"
    rules:
      - operations: ["DELETE"]
        apiGroups: ["k8s.f5net.com"]
        apiVersions: ["*"]
        resources:
          - "f5-big-tcp-settings"
          - "f5-big-udp-settings"
          - "f5-big-fastl4-settings"
          - "f5-big-zerorating-policies"
          - "f5-big-context-globals"
          - "f5-big-ipi-categorylists"
          - "f5-big-dpi-pe-optionses"
          - "f5-big-http2-settings"
          - "f5-big-http-settings"
          - "f5-big-clientssl-settings"
        scope: "Namespaced"
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["k8s.f5net.com", "ingresstcp.k8s.f5net.com", "ingressudp.k8s.f5net.com"]
        apiVersions: ["*"]
        resources:
          - "f5-big-gslb-datacenters"
          - "f5-big-gslb-monitors"
          - "f5-big-gslb-pools"
          - "f5-big-gslb-servers"
          - "f5-big-gslb-topology-groups"
          - "f5-big-gslb-topology-records"
          - "f5-big-gslb-wideips"
          - "f5-big-gslb-instances"
          - "f5-spk-vlans"
          - "f5-spk-vxlans"
          - "f5-big-net-vlans"
          - "f5-spk-ingresstcps"
          - "f5-spk-snatpools"
          - "f5-spk-staticroutes"
          - "f5-spk-egresses"
          - "f5-spk-ingresshttp2s"
          - "f5-spk-ingressudps"
          - "f5-spk-ingressdiameters"
          - "f5-big-cne-irules"
          - "f5-spk-traffic-distributions"
          - "f5-big-cne-zones"
          - "f5-big-net-staticroutes"
          - "f5-big-fw-policies"
          - "f5-big-fw-rulelists"
          - "f5-big-nat-policies"
          - "f5-spk-diameteregresses"
          - "f5-big-svc-policies"
          - "f5-spk-ingressngaps"
          - "f5-big-ike-peers"
          - "f5-spk-statefulsets"
          - "f5-spk-egresshttp2s"
          - "f5-big-snic-pltfm-settings"
          - "f5-big-dns-apps"
          - "f5-big-context-secures"
          - "f5-big-cne-addresslists"
          - "f5-spk-addresslists"
          - "f5-big-radius-attributes"
        scope: "Namespaced"
    sideEffects: None
    admissionReviewVersions: ["v1"]
