{{ $base_port := (.Values.controller.validationService.port | int )}}
apiVersion: v1
kind: Service
metadata:
  name: f5-validation-svc
  labels:
    app: {{ include "f5ingress.appName" . }}
    type: https
    appNamespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "f5ingress.appName" . }}
  ports:
    - protocol: TCP
      name: validation-svc
      port: {{ $base_port }}
      targetPort: {{ $base_port }}
