{{- if and .Values.enabled .Values.tmm.add_k8s_routes }}
{{- if or (.Capabilities.APIVersions.Has "config.openshift.io/v1") (eq .Values.global.platformType "robin") (eq .Values.global.platformType "aon") (eq .Values.global.platformType "generic") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: tmm-k8s-routes-prehook-job-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
    "helm.sh/hook-weight": "4"
spec:
  template:
    spec:
      restartPolicy: Never
{{- if .Values.tmm.create_k8s_routes_sa }}
      serviceAccountName: tmm-k8s-routes-prehook-sa-{{ .Release.Namespace }}
{{- else }}
      serviceAccountName: {{ .Values.tmm.k8s_routes_sa_name }}
{{- end }}
      {{- if and .Values.global.imageCredentials .Values.global.imageCredentials.name }}
      imagePullSecrets:
        - name: {{ .Values.global.imageCredentials.name }}
      {{- else }}
      imagePullSecrets: []
      {{- end }}
      containers:
      - name: tmm-k8s-routes-prehook-container
        image: "{{ .Values.debug.image.repository }}/{{ .Values.debug.image.name }}:{{ .Values.debug.image.tag }}"
        command: ["/bin/sh", "-c"]
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: CNF_CONFIGMAP_NAME
            value: tmm-k8s-routes-configmap
      {{- if .Capabilities.APIVersions.Has "config.openshift.io/v1" }}
        args:
          - -c
          - |

            KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
            RESPONSE=$(curl --header "Authorization: Bearer $KUBE_TOKEN" \
              --insecure \
              "https://kubernetes.default.svc/apis/config.openshift.io/v1/networks/cluster" \
              --silent \
              --verbose)

            echo "service_networks: ${RESPONSE}"

            #Filter the output
            ip_list=""

            #gets service network ips
            initial_filter=$(echo $RESPONSE | sed -n -e 's/^.*status//p') #get everything after last match
            response_filter=$(echo $initial_filter | grep -oP '"serviceNetwork":\K.*') #get everything after match
            response_filter=$(echo $response_filter | grep -oP '(?<=\[).+?(?=\])') #content between []
            response_filter=$(echo $response_filter | sed 's/ //g')  #remove whitespace
            response_filter=$(echo $response_filter | sed 's/"//g')  #remove double quotes "

            ip_list=$response_filter

            cidr=$initial_filter
            while true; do
              cidr=$(echo $cidr | grep -oP '"cidr":\K.*')
              if [ -z "$cidr" ]
              then
                break
              fi

              ip=$(echo $cidr | cut -d "," -f 1)
              ip=$(echo $ip | sed 's/ //g')
              ip=$(echo $ip | sed 's/"//g')

              ip_list="${ip_list},${ip}"
            done

            echo "ip_list ${ip_list}"

            patch='[
              {
                "op": "replace",
                "path": "/data/TMM_K8S_ROUTES",
                "value": '\"${ip_list}\"'
              }
            ]'

            echo "patch: ${patch}"

            curl --request PATCH \
              --header "Authorization: Bearer $KUBE_TOKEN" \
              --header "Content-Type: application/json-patch+json" \
              --data "$patch" \
              --insecure \
              --verbose \
              "https://kubernetes.default.svc/api/v1/namespaces/$POD_NAMESPACE/configmaps/$CNF_CONFIGMAP_NAME-$POD_NAMESPACE"
      {{- else }}
        args:
          - -c
          - |
            KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
            NAMESPACE=kube-system
            CONFIG_MAP=kubeadm-config
            RESPONSE=$(curl --header "Authorization: Bearer $KUBE_TOKEN" \
              --insecure \
              "https://kubernetes.default.svc/api/v1/namespaces/$NAMESPACE/configmaps/$CONFIG_MAP" \
              --silent \
              --verbose)
            echo "service_networks: ${RESPONSE}"

            #gets pod and service networks
            pod_subnet=$(echo $RESPONSE | grep -oP 'podSubnet: \K\S+')
            service_subnet=$(echo $RESPONSE | grep -oP 'serviceSubnet: \K\S+' | awk -F 'scheduler' '{print $1}')

            ip_list="$pod_subnet,$service_subnet"
            {{- if (eq .Values.global.platformType "aon") }}
              DNS_CONFIG_MAP=node-local-dns
              DNS_RESPONSE=$(curl --header "Authorization: Bearer $KUBE_TOKEN" \
                --insecure \
                https://kubernetes.default.svc/api/v1/namespaces/$NAMESPACE/configmaps/$DNS_CONFIG_MAP \
                --silent \
                --verbose)
              echo "dns_config_map: ${DNS_RESPONSE}"
              dns_bind_addr=$(echo $DNS_RESPONSE | grep -oP 'bind \K[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)/32
              ip_list="$ip_list,$dns_bind_addr"
            {{- end }}
            echo "ip_list ${ip_list}"

            patch='[
              {
                "op": "replace",
                "path": "/data/TMM_K8S_ROUTES",
                "value": '\"${ip_list}\"'
              }
            ]'

            echo "patch: ${patch}"

            curl --request PATCH \
              --header "Authorization: Bearer $KUBE_TOKEN" \
              --header "Content-Type: application/json-patch+json" \
              --data "$patch" \
              --insecure \
              --verbose \
              "https://kubernetes.default.svc/api/v1/namespaces/$POD_NAMESPACE/configmaps/$CNF_CONFIGMAP_NAME-$POD_NAMESPACE"
      {{- end }}
{{- end }}
{{- end }}
