{{- if not .Values.controller.Only }}
{{- if and .Values.enabled .Values.tmm.add_k8s_routes }}
{{- if or (.Capabilities.APIVersions.Has "config.openshift.io/v1") (eq .Values.global.platformType "robin") (eq .Values.global.platformType "aon") (eq .Values.global.platformType "generic") }}
{{- if .Values.tmm.create_k8s_routes_sa }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tmm-k8s-routes-prehook-sa-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
{{- end }}
{{- end }}
{{- end }}
{{- end }}
