# Check if the Certificate CRD is present in the cluster.
{{ $f5cert := lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "certificates.cm.f5co.k8s.f5net.com" }}
{{ $certmgr := lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "certificates.cert-manager.io" }}
{{- if or $certmgr $f5cert }}
{{- if (index .Values "cert-orchestrator" "enabled") }}
{{- if and (.Values.enabled) (.Values.debug.enabled)}}
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-debug-grpc-clt
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-debug-grpc-clt-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate is 1 hour, not configurable
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
---
#certificate for communication from CWC Orchestrator to Qkview process
{{- if and (.Values.debug.enabled) (.Values.debug.f5_csm_qkview.enabled)}}
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-f5-debug-sidecar-grpc-svr
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  dnsNames:
     - f5-tmm.{{ .Release.Namespace }}
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-f5-debug-sidecar-grpc-svr-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate is 1 hour, not configurable
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
{{- end }}
{{- end }}
---
#certificate for communication from CWC Orchestrator to Qkview process
{{- if and (.Values.tmm.dynamicRouting.enabled) (.Values.tmrouted.f5_csm_qkview.enabled)}}
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-f5-tmrouted-grpc-svr
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  dnsNames:
     - f5-tmm.{{ .Release.Namespace }}
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-f5-tmrouted-grpc-svr-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate is 1 hour, not configurable
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
{{- end }}
---
{{- if (.Values.blobd.enabled) }}
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-blobd-grpc-clt
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-blobd-grpc-clt-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate is 1 hour, not configurable
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
---
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-blobd-grpc-svr
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  dnsNames:
    - grpc-svc
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-blobd-grpc-svr-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate is 1 hour, not configurable
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
{{- end }}
---
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-tmm-grpc-svr
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  dnsNames:
    - grpc-svc
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-tmm-grpc-svr-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate is 1 hour, not configurable
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
---
#certificate for communication from CWC Orchestrator to Qkview process
{{- if .Values.tmm.f5_csm_qkview.enabled }}
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-tmm-qkview-grpc-svr
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  dnsNames:
     - f5-tmm.{{ .Release.Namespace }}
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-tmm-qkview-grpc-svr-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate is 1 hour, not configurable
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
{{- end }}
---
{{- if (eq .Values.tmm.sessiondb.useExternalStorage "true") }}
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-tmm-mds-clt
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  dnsNames:
    - dssm-svc
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-tmm-mds-clt-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate. 1 hour.
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
{{- end }}
---
{{- if (eq .Values.tmm.sessiondb.useExternalStorage "true") }}
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-debug-mds-clt
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  dnsNames:
    - dssm-svc
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-debug-mds-clt-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate. 1 hour.
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
{{- end }}
---
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-debug-amqp-clt
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  commonName: f5net
  dnsNames:
    - f5net
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-debug-amqp-clt-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate is 1 hour, not configurable
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
---
#certificate for communication from qkview orchestrator to Qkview process
{{- if (.Values.f5_csm_qkview.enabled) }}
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-dynamic-routing-grpc-svr
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  dnsNames:
     - f5-tmm.{{ .Release.Namespace }}
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-dynamic-routing-grpc-svr-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  # Lifetime of the Certificate. 360 days(long-lived).
  duration: 1h
  revisionHistoryLimit: 10
{{- end }}
{{- end }}
---
#certificate for communication from CWC Orchestrator to Qkview process
{{- if (.Values.blobd.f5_csm_qkview.enabled) }}
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-qkview-blobd-grpc-svr
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  dnsNames:
     - f5-tmm.{{ .Release.Namespace }}
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-qkview-blobd-grpc-svr-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate is 1 hour, not configurable
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
{{- end }}
{{- end }}
---
{{- if (include "enableObserver" . | lower | eq "true") }}
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: {{ .Values.observer.name }}
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  dnsNames:
    - f5-tmm.{{ .Release.Namespace }}
    - {{ .Values.observer.name }}
    - {{ .Values.observer.name }}.{{ .Release.Namespace }}
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: {{ .Values.observer.name }}-cert-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate is 1 hour, not configurable
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10 
{{- end }}
---
{{- if .Values.fluentbit.enabled }}
{{- if .Values.global.certmgr.external }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: cm.f5co.k8s.f5net.com/v1
{{- end }}
kind: Certificate
metadata:
  name: tls-genericfluentbit-tcp-clt
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    countries:
      - US
    provinces:
      - Washington
    localities:
      - Seattle
    organizations:
      - F5 Networks
    organizationalUnits:
      - PD
  emailAddresses:
    - clientcert@f5net.com
  commonName: f5net.com
  # SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource.
  # It will be populated with a private key and certificate, signed by the denoted issuer.
  secretName: tls-genericfluentbit-tcp-clt-secret
  # IssuerRef is a reference to the issuer for this certificate.
  {{- if .Values.global.certmgr.external }}
  issuerRef: {{ toYaml .Values.global.certmgr.issuerRef | nindent 4 }}
  {{- else }}
  issuerRef:
    name: default-cert-issuer
    kind: ClusterIssuer
  {{- end }}
  # Lifetime of the Certificate is 360 days, not configurable
  duration: 1h
  privateKey:
    rotationPolicy: Always
    encoding: PKCS1
    algorithm: RSA
    size: 4096
  revisionHistoryLimit: 10
{{- end }}
