{{- if and .Values.enabled .Values.global.tmm.grpc.enabled }}
{{ $base_port := (.Values.global.bdosd.grpc.port | int )}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.bdosd.grpc.name }}
  labels:
    app: {{ .Values.bdosd.name }}
    type: grpc
spec:
  selector:
    app: {{ .Values.bdosd.name }}
  ports:
    - protocol: TCP
      name: grpc-bdosd
      port: {{ $base_port }}
      targetPort: {{ $base_port }}
{{- end }}
---
{{- if .Values.bdosd.f5_csm_qkview.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: f5-bdosd
  labels:
    app: {{ .Values.bdosd.name }}
spec:
  ports:
  - port: {{ .Values.bdosd.f5_csm_qkview.grpc_port }}
    name: grpc-port-qkview
    protocol: TCP
    targetPort: {{ .Values.bdosd.f5_csm_qkview.grpc_port }}
  selector:
    app: {{ .Values.bdosd.name }}
{{- end }}
